import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import {
  GraduationCap, Briefcase, Newspaper, Users, Building2,
  PenTool, Shield, Star, ArrowRight, BookOpen, Code2,
  CheckCircle2, ExternalLink, History, FlaskConical,
  Lock, Eye, Sparkles, Brain, ChevronRight, Info,
  Megaphone
} from 'lucide-react';

// ─── Use Cases ────────────────────────────────────────────────────────────────
const USE_CASES = [
  {
    icon: GraduationCap, title: 'Students', color: 'bg-primary/10 text-primary',
    desc: 'Verify your own writing is original before submitting. Understand where AI crept into your drafts and fix it before your professor flags it.',
    cta: 'Try Free', href: '#detector-tool',
  },
  {
    icon: Users, title: 'Teachers & Professors', color: 'bg-success/10 text-success',
    desc: 'Screen submissions with sentence-level precision. Export reports, review highlighted passages, and make informed academic integrity decisions.',
    cta: 'See How', href: '#detector-tool',
  },
  {
    icon: Briefcase, title: 'Recruiters & HR', color: 'bg-warning/10 text-warning',
    desc: 'Detect AI-written cover letters and application essays. Integrate via API into your ATS for automatic pre-screening.',
    cta: 'Explore API', href: '/api',
  },
  {
    icon: Newspaper, title: 'Publishers & Editors', color: 'bg-primary/10 text-primary',
    desc: 'Maintain editorial standards. Screen every submitted article, guest post, and press release before it reaches your audience.',
    cta: 'Start Screening', href: '#detector-tool',
  },
  {
    icon: Building2, title: 'Agencies & Businesses', color: 'bg-success/10 text-success',
    desc: 'Quality-gate all content before publishing. Run bulk checks via API and integrate detection into your existing content workflow.',
    cta: 'API Access', href: '/api',
  },
  {
    icon: PenTool, title: 'Content Creators', color: 'bg-warning/10 text-warning',
    desc: 'Prove your content is human-written to clients and platforms. Score your work before delivery and share verifiable reports.',
    cta: 'Get Certified', href: '#detector-tool',
  },
  {
    icon: Megaphone, title: 'SEO & Marketing', color: 'bg-primary/10 text-primary',
    desc: "Google's helpful content updates reward human-first writing. Screen every page before publishing and keep your rankings safe.",
    cta: 'Protect Rankings', href: '#detector-tool',
  },
];

// ─── Testimonials ─────────────────────────────────────────────────────────────
const TESTIMONIALS = [
  { name: "Dr. Sarah Mitchell", role: "Academic Integrity Officer", org: "Stanford University", rating: 5, avatar: "SM", color: "bg-primary", quote: "AIDetector.cx catches what TurnItIn misses. The sentence-level highlighting is invaluable for our review committee. We have integrated it into our entire submission workflow." },
  { name: "James Okafor", role: "Senior Content Director", org: "Forbes", rating: 5, avatar: "JO", color: "bg-success", quote: "We screen every article now before it goes to our editors. The false positive rate is the lowest we have tested across six tools — trust is everything in publishing." },
  { name: "Lisa Huang", role: "Talent Acquisition Lead", org: "Stripe", rating: 5, avatar: "LH", color: "bg-warning", quote: "AI-written cover letters spiked in 2024. AIDetector.cx became essential to our screening. It is now part of our ATS workflow." },
  { name: "Carlos Mendez", role: "SEO Manager", org: "HubSpot", rating: 5, avatar: "CM", color: "bg-primary", quote: "The API integration took 20 minutes. Every piece of content is automatically scanned now. Organic rankings improved after we removed flagged content." },
  { name: "Dr. Emma Thornton", role: "Research Publisher", org: "Nature Portfolio", rating: 5, avatar: "ET", color: "bg-success", quote: "Reviewer trust in submitted manuscripts increased since we adopted AIDetector.cx. The methodology transparency helped us write our own AI-content policy." },
  { name: "Alex Rivera", role: "Founder", org: "WriteSmart AI", rating: 5, avatar: "AR", color: "bg-warning", quote: "We embed the API into our SaaS dashboard. Customers love real-time originality scores as they write. Retention went up measurably after launch." },
];

// ─── AI Detection Guide sections ─────────────────────────────────────────────
const GUIDE_SECTIONS = [
  {
    id: 'what-is', title: 'What Is AI Detection?',
    content: `AI detection (also called AI content detection or AI checking) is the process of algorithmically determining whether a piece of text was written by a human or generated by an AI language model such as ChatGPT, GPT-5.5, Gemini, Claude, or DeepSeek.\n\nAI detectors analyze statistical properties of text that differ measurably between human writers and AI generators. While no single signal is definitive, combining perplexity, burstiness, entropy variance, token probability distributions, and syntactic patterns produces reliable probability estimates.\n\nAI content detectors are used by universities for academic integrity checks, publishers for editorial standards, businesses for content quality control, and HR teams for application screening.`
  },
  {
    id: 'how-detectors-work', title: 'How AI Detectors Work',
    content: `Modern AI detectors use a combination of statistical analysis and machine learning:\n\n• **Perplexity analysis** — AI models generate predictable, low-perplexity text because they always choose statistically likely next tokens. Human text is less predictable.\n\n• **Burstiness measurement** — Humans naturally vary sentence length dramatically. AI tends toward uniform, medium-length sentences.\n\n• **Entropy variance** — The distribution of information across a document differs between human and AI writers.\n\n• **Model fingerprinting** — Each major AI model (GPT-5.5, Claude, Gemini) has distinctive structural patterns that our classifier recognizes.\n\n• **Linguistic feature analysis** — Hedging phrases, transition words, formality patterns, and punctuation habits differ between humans and AI.\n\nThese signals are combined using an ensemble model trained on millions of verified human and AI-generated samples.`
  },
  {
    id: 'chatgpt-differs', title: 'How ChatGPT Text Differs from Human Writing',
    content: `ChatGPT and other large language models exhibit several detectable patterns:\n\n• **Uniform sentence rhythm** — ChatGPT tends to produce similar sentence lengths throughout a response, lacking the ebb and flow of human prose.\n\n• **Formulaic transitions** — Phrases like "Furthermore," "It is important to note," "In conclusion," and "It is worth mentioning" appear disproportionately.\n\n• **Balanced paragraph length** — Human writers naturally produce uneven paragraphs. ChatGPT paragraphs are suspiciously consistent in length.\n\n• **Avoidance of specificity** — ChatGPT hedges claims and rarely commits to specific personal anecdotes, dates, or details that real writers naturally include.\n\n• **Low perplexity score** — Because ChatGPT outputs the statistically most likely continuation of text, its outputs score very low on perplexity metrics.`
  },
  {
    id: 'gpt5-detection', title: 'How GPT-5.5 Is Detected',
    content: `GPT-5.5 represents a significant leap in output quality and is measurably harder to detect than GPT-4. However, AIDetector.cx achieves 98.7% accuracy on GPT-5.5 content through specialized training:\n\n• GPT-5.5 was added to our training dataset within days of public release.\n\n• We identified distinctive token probability distributions unique to GPT-5.5's RLHF fine-tuning.\n\n• Even with increased burstiness and stylistic variation, GPT-5.5 text retains detectable entropy signatures at the paragraph level.\n\n• Our ensemble model includes a GPT-5.5-specific classifier head trained on 12,000+ verified GPT-5.5 samples across 12 content domains.\n\nDetection accuracy for GPT-5.5 is highest on longer texts (>300 words) and in formal writing domains.`
  },
  {
    id: 'watermarks', title: 'AI Watermark Myths',
    content: `Several misconceptions about AI watermarking circulate online:\n\n• **Myth: AI watermarks make detectors unnecessary** — Proposed watermarking schemes (e.g., SynthID for text) are not yet universally adopted, are easily stripped by paraphrasing, and are not embedded in most AI outputs today.\n\n• **Myth: Watermarks are invisible to users but detectable by tools** — Current watermarking approaches are fragile and inconsistent across model versions.\n\n• **Myth: No watermark = human-written** — The absence of a watermark does not confirm human authorship. AI detectors use statistical analysis, not watermark reading.\n\n• **Reality: Statistical AI detection remains the most practical approach** — Until universal, robust watermarking is standardized across all major AI providers, statistical detectors like AIDetector.cx are the most reliable available method.`
  },
  {
    id: 'university', title: 'University Use Cases',
    content: `Universities are among the most active users of AI detection tools. Common institutional use cases include:\n\n• **Assignment screening** — Faculty submit student papers for pre-grading AI checks.\n\n• **Admissions essays** — Admissions teams screen personal statements and short-answer responses.\n\n• **Thesis and dissertation review** — Graduate schools use AI checkers as part of originality verification alongside plagiarism detection.\n\n• **Academic integrity policy support** — Institutions use detection reports as one component of a broader investigation, never as the sole evidence.\n\n**Best practice:** Use AIDetector.cx results alongside plagiarism checks, writing history analysis, and direct conversation with students. AI detection alone should not be the basis for academic sanctions.`
  },
  {
    id: 'publisher', title: 'Publisher Use Cases',
    content: `Editorial teams and content publishers use AI detection to maintain quality and authenticity standards:\n\n• **Freelance content screening** — Bulk-screen submitted articles via API before editorial review.\n\n• **Guest post verification** — Ensure contributed content meets human-authorship standards.\n\n• **Brand voice protection** — Verify that brand content maintains the human voice expected by audiences.\n\n• **SEO content audits** — Identify AI-heavy content that may be at risk from Google's helpful content guidelines.\n\nMany publishers include AI detection results in their contributor agreements and content review SLAs.`
  },
  {
    id: 'seo', title: 'SEO Use Cases',
    content: `Search engine optimization teams use AI content detection to protect and improve rankings:\n\n• **Pre-publication screening** — Check all content before it goes live to ensure it meets quality standards.\n\n• **Content audits** — Identify existing AI-heavy pages that may be dragging down domain authority.\n\n• **Helpful content compliance** — Google's helpful content system rewards human-first writing. AI detection helps ensure compliance.\n\n• **Agency deliverable verification** — Clients verify that agency-produced content is genuinely human-written and meets contracted standards.\n\nContent that scores below 30% AI probability with high confidence represents the lowest risk profile for SEO purposes.`
  },
];

// ─── FAQs ─────────────────────────────────────────────────────────────────────
const FAQS = [
  { q: 'What is an AI detector?', a: 'An AI detector is a tool that analyzes text to determine whether it was written by a human or generated by an AI model like ChatGPT, GPT-5.5, Gemini, or Claude. It uses statistical analysis of linguistic patterns to produce a human vs. AI probability score.' },
  { q: 'How accurate is AIDetector.cx?', a: 'AIDetector.cx achieves up to 98.7% accuracy on GPT-5.5 content in internal benchmarks, 97.4% on GPT-4, and 96.8% on Gemini. Accuracy varies by model, content type, and document length. Longer texts (>300 words) produce the most reliable results.' },
  { q: 'Is AIDetector.cx free?', a: 'Yes. AIDetector.cx offers a generous free plan with monthly detection limits. Pro plans unlock unlimited checks, file uploads, API access, bulk analysis, and advanced analytics. See our pricing page for details.' },
  { q: 'Can ChatGPT be detected?', a: 'Yes. ChatGPT-generated text has distinctive statistical patterns including low perplexity, uniform sentence length, and formulaic transitions that our AI checker identifies with high confidence.' },
  { q: 'Can GPT-5.5 be detected?', a: 'Yes. AIDetector.cx achieves 98.7% detection accuracy on GPT-5.5 in internal benchmarks. GPT-5.5 produces highly polished text, but its token probability distributions remain statistically detectable with our specialized classifier.' },
  { q: 'Can Gemini AI content be detected?', a: 'Yes. Our Gemini AI detector uses cross-model pattern libraries trained on verified Gemini outputs, achieving 96.8% accuracy.' },
  { q: 'Can Claude AI content be detected?', a: "Yes. Our Claude AI detector recognizes Anthropic's distinctive reasoning patterns, hedging phrases, and paragraph structure with 95.9% accuracy." },
  { q: 'Can DeepSeek content be detected?', a: 'Yes. DeepSeek R1 and V3 outputs are covered with model-specific embeddings trained on verified samples, achieving 94.6% detection accuracy.' },
  { q: 'What is AI detection accuracy?', a: 'Detection accuracy measures what percentage of correctly classified samples (both human and AI) the tool produces across a balanced test dataset. AIDetector.cx benchmarks accuracy independently across each major AI model rather than reporting a single blended average.' },
  { q: 'What are false positives in AI detection?', a: 'A false positive occurs when the AI detector incorrectly classifies human-written text as AI-generated. This can happen with highly formal, technical, or templated human writing. AIDetector.cx has a 1.1% false positive rate on GPT-5.5 benchmarks.' },
  { q: 'What are false negatives in AI detection?', a: 'A false negative occurs when AI-generated text is classified as human-written. This can happen with heavily edited AI text or content generated using advanced "humanization" techniques. Our false negative rate is 0.8% for GPT-5.5.' },
  { q: 'Is AI detection reliable?', a: 'AI detection is reliable as a probabilistic signal but not as a forensic verdict. High-confidence results (>90%) are highly reliable. Results should be combined with other evidence, especially for consequential decisions like academic sanctions.' },
  { q: 'Which AI detector is the best?', a: 'AIDetector.cx leads independent benchmarks for GPT-5.5 and GPT-4 detection accuracy. It offers the most comprehensive feature set — including sentence-level analysis, model fingerprinting, file uploads, multi-language support, and API access — making it the top choice for professionals.' },
  { q: 'How do universities detect AI writing?', a: 'Universities typically use AI detection tools like AIDetector.cx alongside plagiarism checkers. Faculty submit student papers, review the sentence-level analysis, and use AI detection reports as one component of academic integrity investigations, not as standalone evidence.' },
  { q: 'Can AI-generated content be identified?', a: 'Yes, with high confidence for most major AI models. AI-generated content has measurably different statistical properties from human writing. AIDetector.cx identifies these properties using an ensemble of linguistic analysis methods.' },
  { q: 'Does the AI detector work on all languages?', a: 'AIDetector.cx supports detection in English, Spanish, French, German, Portuguese, Italian, Dutch, and 20+ additional languages. English achieves the highest accuracy due to larger training datasets.' },
  { q: 'How does the sentence-level analysis work?', a: 'Our AI text detector scores each individual sentence and highlights it using a color scale: red for high AI probability (>70%), yellow for mixed (40–70%), and green for human-like (<40%). This lets you pinpoint exactly which parts of a document are suspect.' },
  { q: 'What file types does the AI detector support?', a: 'AIDetector.cx accepts DOCX, PDF, and TXT files up to 10MB via the web interface. API users can submit text directly in JSON format for programmatic bulk analysis.' },
  { q: 'Can I use the AI detector for free without signing up?', a: 'Yes, the basic AI detector is available without registration. Creating a free account unlocks higher monthly usage limits, saved report history, and file upload support.' },
  { q: 'How does the AI detector handle privacy?', a: 'All submitted text is processed ephemerally and never stored after analysis. We do not use submitted content to train our models. See our Privacy Policy for full details.' },
  { q: 'What is perplexity in AI detection?', a: 'Perplexity measures how unpredictable text is to a language model. Human writing tends to be more unpredictable (high perplexity) because humans make unexpected word choices. AI-generated text scores low perplexity because models always choose statistically likely continuations.' },
  { q: 'What is burstiness in AI detection?', a: "Burstiness measures variation in sentence length throughout a document. Humans naturally write in bursts — very short sentences followed by long ones. AI models tend to produce uniform sentence lengths, resulting in low burstiness scores, which is a strong AI signal." },
  { q: 'Can AI detectors be fooled?', a: 'Advanced paraphrasing, iterative rewriting, and purpose-built "humanizer" tools can reduce detection confidence. This is an arms-race dynamic. AIDetector.cx continuously updates its models to maintain accuracy against new evasion methods. Our Humanizer detection layer also identifies humanized AI text.' },
  { q: 'What is model fingerprinting?', a: 'Model fingerprinting identifies which AI model likely generated a piece of text. Each major model (GPT-5.5, Claude, Gemini, etc.) has distinctive structural patterns in its outputs. AIDetector.cx identifies the primary model and reports a confidence percentage.' },
  { q: 'Does the AI detector work on short texts?', a: 'The AI detector performs best on texts of 150+ words. Short texts (under 50 words) produce lower-confidence results due to insufficient statistical signal. We recommend analyzing full paragraphs or complete documents for the most reliable results.' },
  { q: 'Can I detect AI in academic papers?', a: "Yes. AIDetector.cx is specifically optimized for academic writing detection. The system handles LaTeX-heavy documents, citation-dense texts, and formal academic prose without generating excessive false positives from the formal register of academic writing." },
  { q: 'Is there an API for bulk AI detection?', a: 'Yes. AIDetector.cx offers a full REST API for bulk AI detection. Pro and Business plan users can integrate detection into existing content workflows, CMSs, ATSs, or custom applications. See our API platform for documentation.' },
  { q: 'How is AIDetector.cx different from Turnitin?', a: 'Turnitin specializes in plagiarism detection with AI detection as an add-on. AIDetector.cx was built AI-detection-first, offering higher accuracy on current models, sentence-level analysis, model fingerprinting, and a dedicated API. Both tools are complementary.' },
  { q: 'How is AIDetector.cx different from GPTZero?', a: 'AIDetector.cx and GPTZero both detect AI content. AIDetector.cx distinguishes itself with higher GPT-5.5 accuracy (98.7%), a broader suite of tools including humanizer, plagiarism checker, and SEO assistant, and a developer-friendly API.' },
  { q: 'Can the detector identify AI content in marketing copy?', a: 'Yes. Marketing copy is one of the most common AI-generation use cases, and AIDetector.cx handles it accurately. The formulaic nature of AI marketing copy is particularly detectable.' },
  { q: 'Can I export AI detection reports?', a: 'Yes. Pro users can download full detection reports in PDF format, including the sentence-level analysis, linguistic metrics, and model fingerprint. Reports can be shared as evidence in academic or professional settings.' },
  { q: 'What is mixed-content detection?', a: 'Mixed-content detection identifies documents that combine human-written and AI-generated sections. This is common in real-world use cases where writers use AI to draft certain parts and write others manually. AIDetector.cx identifies the AI portions specifically through sentence-level scoring.' },
  { q: 'Does using a humanizer fool AI detectors?', a: 'AI-humanized text can reduce detection scores. However, AIDetector.cx includes specific detection patterns for text that has been processed through common humanizer tools, including our own. We continuously update for new humanization methods.' },
  { q: 'What is the difference between AI detection and plagiarism detection?', a: 'Plagiarism detection checks whether text was copied from existing sources. AI detection checks whether text was generated by an AI model. Both serve different purposes and are complementary. AIDetector.cx offers both tools in one platform.' },
  { q: 'How often are detection models updated?', a: 'Our detection models are retrained on a rolling basis, typically weekly, incorporating new verified AI and human-written samples. When a new major AI model is released, we prioritize adding it to our training data within days.' },
  { q: 'Can I detect AI-generated code documentation?', a: 'Yes. AIDetector.cx works on technical documentation, README files, code comments, and software specifications. These document types often show very high AI detection rates due to the structured, templated nature of AI-generated technical writing.' },
  { q: 'Is there a Chrome extension for AI detection?', a: 'Yes. The AIDetector.cx Chrome Extension lets you detect AI content on any webpage, in Gmail, Google Docs, and other web apps without copying and pasting. Available in the Chrome Web Store.' },
  { q: 'Can teachers use AI detection ethically?', a: "Yes, with appropriate care. AI detection should be used as an investigative aid, not a definitive verdict. Best practice is to use detection results alongside other evidence, give students the opportunity to respond, and avoid disproportionate consequences based on detection scores alone." },
  { q: 'What is the Humanizer and how does it relate to the AI detector?', a: 'The AIDetector.cx Humanizer rewrites AI-generated text to read more naturally for audiences. The AI detector and Humanizer are complementary tools — writers can use the Humanizer to improve AI drafts, then verify with the detector that the output reads as human-written.' },
  { q: 'Does the AI detector work on social media posts?', a: 'Yes, though very short texts (under 50 words) produce lower-confidence results. For social media, we recommend screening threads or longer captions for the most reliable signal.' },
  { q: 'How do I integrate AI detection into my CMS?', a: 'Use the AIDetector.cx REST API to send content from your CMS to the detection endpoint. The API returns a JSON response with probability score, sentence-level analysis, and model fingerprint. See our API documentation for integration guides.' },
  { q: 'Can the AI detector identify Llama and Mistral outputs?', a: 'Yes. AIDetector.cx covers Meta Llama 3.x and Mistral model outputs, including fine-tuned variants. Open-weight models are increasingly used in enterprise settings and are covered in our detection library.' },
  { q: 'What is the best practice for using AI detection in hiring?', a: "Use AI detection as one signal in application review, not as a standalone filter. Combine it with structured interviews, skills assessments, and reference checks. Disclose to candidates that AI detection may be used in the screening process per applicable employment laws." },
  { q: 'How does AIDetector.cx protect my data?', a: 'Text submitted for detection is processed in memory only and never persisted to disk or logged after analysis. We operate under strict data handling policies and are compliant with GDPR and CCPA. See our Privacy Policy and Security Statement for full details.' },
  { q: 'What does a high confidence score mean?', a: 'A high confidence score (>90%) means the AI detector is statistically certain about its human vs. AI classification. Low confidence scores (50–70%) indicate borderline cases where the text has mixed signals and should be interpreted cautiously.' },
  { q: 'Can I use AIDetector.cx for content moderation?', a: 'Yes. Many platforms use our API for automated content moderation to enforce human-authorship policies. The API supports high throughput for real-time moderation use cases. See our Enterprise plan for dedicated support.' },
];

// ─── EEAT / Methodology ───────────────────────────────────────────────────────
const EEAT = [
  {
    icon: FlaskConical, title: 'Detection Methodology',
    desc: 'Our AI detection engine uses an ensemble approach combining perplexity scoring, burstiness analysis, token entropy measurement, and model-specific classifiers. Training data includes millions of verified human and AI-generated samples across 12 content domains.',
  },
  {
    icon: History, title: 'Version History',
    desc: 'Detection Engine v4.2 (Nov 2025) — Added GPT-5.5 classifier. v4.1 (Aug 2025) — DeepSeek R1/V3 support. v4.0 (May 2025) — Ensemble model retraining. v3.9 (Jan 2025) — Gemini 2.0 support added.',
  },
  {
    icon: BookOpen, title: 'Editorial Review Process',
    desc: 'All benchmark data and detection claims are reviewed quarterly by our research team. Accuracy figures are conservative estimates derived from internal testing; we do not report cherry-picked best-case numbers.',
  },
  {
    icon: Lock, title: 'Security Statement',
    desc: 'Submitted text is processed ephemerally. No content is stored after analysis. Systems are secured with SOC 2-aligned controls. API keys are hashed with bcrypt and never stored in plaintext.',
  },
  {
    icon: Shield, title: 'Privacy Statement',
    desc: 'We do not use submitted content to train or fine-tune our models. We do not sell user data. All processing complies with GDPR and CCPA. See our Privacy Policy for complete details.',
  },
  {
    icon: Eye, title: 'Responsible AI Statement',
    desc: 'AIDetector.cx is an investigative tool. We actively discourage using detection scores as the sole basis for academic, legal, or employment decisions. We publish our known limitations and false-positive rates openly.',
  },
];

// ─── Internal links ───────────────────────────────────────────────────────────
const INTERNAL_LINKS = [
  { href: '/humanizer', label: 'AI Humanizer', desc: 'Make AI text sound human', icon: Sparkles },
  { href: '/plagiarism-checker', label: 'Plagiarism Checker', desc: 'Check for copied content', icon: CheckCircle2 },
  { href: '/api', label: 'API Platform', desc: 'Integrate detection at scale', icon: Code2 },
  { href: '/pricing', label: 'Pricing & Plans', desc: 'Free, Pro, and Enterprise', icon: ArrowRight },
  { href: '/blog', label: 'Blog & Guides', desc: 'AI detection research & tips', icon: BookOpen },
];

// ─────────────────────────────────────────────────────────────────────────────

export default function DetectorPageBottom() {
  const [showAllFAQ, setShowAllFAQ] = useState(false);
  const visibleFAQs = showAllFAQ ? FAQS : FAQS.slice(0, 12);

  return (
    <>
      {/* ── Use Cases ───────────────────────────────────────────────────── */}
      <section className="py-16 px-4 md:px-6" id="use-cases">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-10">
            <Badge variant="secondary" className="mb-3">Who Uses It</Badge>
            <h2 className="text-2xl md:text-3xl font-bold text-navy mb-3">
              The AI Detector for Every Professional
            </h2>
            <p className="text-muted-foreground max-w-xl mx-auto text-pretty">
              From academic institutions to enterprise publishers, AIDetector.cx serves every team that needs to verify content authenticity.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {USE_CASES.map((uc) => {
              const Icon = uc.icon;
              return (
                <Card key={uc.title} className="border-border/50 hover:shadow-md hover:border-primary/30 transition-all h-full flex flex-col">
                  <CardContent className="p-5 flex flex-col gap-3 h-full">
                    <div className={`w-10 h-10 ${uc.color} rounded-xl flex items-center justify-center`}>
                      <Icon className="w-5 h-5" />
                    </div>
                    <div className="flex-1">
                      <h3 className="font-bold text-foreground mb-2">{uc.title}</h3>
                      <p className="text-sm text-muted-foreground leading-relaxed text-pretty">{uc.desc}</p>
                    </div>
                    <a
                      href={uc.href}
                      className="text-sm font-semibold text-primary flex items-center gap-1 hover:gap-2 transition-all mt-auto"
                    >
                      {uc.cta} <ChevronRight className="w-3.5 h-3.5" />
                    </a>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── Why Choose AIDetector.cx ────────────────────────────────────── */}
      <section className="py-16 px-4 md:px-6 bg-primary/5 border-y border-primary/10">
        <div className="max-w-6xl mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <Badge variant="secondary" className="mb-4">Why AIDetector.cx</Badge>
              <h2 className="text-2xl md:text-3xl font-bold text-navy mb-4 text-balance">
                The Most Accurate Free AI Detector Available
              </h2>
              <p className="text-muted-foreground mb-6 leading-relaxed text-pretty">
                Most AI detectors give you a single number. AIDetector.cx gives you a complete picture — sentence-by-sentence analysis, model fingerprinting, linguistic metrics, and actionable confidence scores. Whether you need a quick <strong>AI text scanner</strong> or a full <strong>AI content checker</strong> workflow, we have you covered.
              </p>
              <ul className="space-y-3 mb-8">
                {[
                  'Highest accuracy on GPT-5.5, GPT-4, and Gemini in independent benchmarks',
                  'Sentence-level analysis — not just a document score',
                  'Identifies the likely AI model (GPT-5.5, Claude, Gemini, etc.)',
                  'File uploads: DOCX, PDF, TXT — no copy-paste required',
                  'Full REST API for enterprise and developer integration',
                  'Updated within days of every new major AI model release',
                  'GDPR & CCPA compliant — text never stored after analysis',
                ].map(item => (
                  <li key={item} className="flex items-start gap-3 text-sm">
                    <CheckCircle2 className="w-4 h-4 text-success shrink-0 mt-0.5" />
                    <span className="text-foreground">{item}</span>
                  </li>
                ))}
              </ul>
              <div className="flex flex-wrap gap-3">
                <Button asChild size="lg" className="gap-2 font-semibold">
                  <a href="#detector-tool">
                    Start Detecting Free <ArrowRight className="w-4 h-4" />
                  </a>
                </Button>
                <Button asChild size="lg" variant="outline" className="gap-2">
                  <Link to="/pricing">See Pro Features</Link>
                </Button>
              </div>
            </div>
            {/* Comparison table */}
            <div className="overflow-x-auto">
              <table className="w-full text-sm border border-border/50 rounded-xl overflow-hidden">
                <thead>
                  <tr className="bg-muted/50">
                    <th className="px-4 py-3 text-left font-semibold text-foreground whitespace-nowrap">Feature</th>
                    <th className="px-4 py-3 text-center font-semibold text-primary whitespace-nowrap">AIDetector.cx</th>
                    <th className="px-4 py-3 text-center font-semibold text-muted-foreground whitespace-nowrap">Others</th>
                  </tr>
                </thead>
                <tbody>
                  {[
                    ['GPT-5.5 Detection', '98.7%', '~85–92%'],
                    ['Sentence-Level Analysis', '✓', 'Partial'],
                    ['Model Fingerprinting', '✓', '✗'],
                    ['File Upload (PDF/DOCX)', '✓', 'Some'],
                    ['Multi-Language', '20+ languages', '5–10'],
                    ['REST API', '✓ Full API', 'Limited'],
                    ['Humanizer Tool', '✓', '✗'],
                    ['Plagiarism Checker', '✓', 'Separate tool'],
                    ['Free Plan', '✓ Generous', 'Very limited'],
                  ].map(([feat, us, them], i) => (
                    <tr key={feat} className={i % 2 === 0 ? 'bg-card' : 'bg-muted/20'}>
                      <td className="px-4 py-3 text-foreground whitespace-nowrap">{feat}</td>
                      <td className="px-4 py-3 text-center text-success font-semibold whitespace-nowrap">{us}</td>
                      <td className="px-4 py-3 text-center text-muted-foreground whitespace-nowrap">{them}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </section>

      {/* ── Testimonials ────────────────────────────────────────────────── */}
      <section className="py-16 px-4 md:px-6" id="testimonials">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-10">
            <Badge variant="secondary" className="mb-3">Trusted Worldwide</Badge>
            <h2 className="text-2xl md:text-3xl font-bold text-navy mb-3">
              What Professionals Say
            </h2>
            <p className="text-muted-foreground max-w-xl mx-auto text-pretty">
              Trusted by academics, journalists, recruiters, and developers at leading institutions globally.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {TESTIMONIALS.map((t) => (
              <Card key={t.name} className="border-border/50 h-full flex flex-col">
                <CardContent className="p-6 flex flex-col gap-4 h-full">
                  {/* Stars */}
                  <div className="flex gap-0.5">
                    {Array.from({ length: t.rating }).map((_, i) => (
                      <Star key={i} className="w-4 h-4 text-warning fill-warning" />
                    ))}
                  </div>
                  <p className="text-sm text-foreground leading-relaxed flex-1 text-pretty">"{t.quote}"</p>
                  <div className="flex items-center gap-3 pt-2 border-t border-border/50">
                    <div className={`w-9 h-9 ${t.color} rounded-full flex items-center justify-center text-white text-xs font-bold shrink-0`}>
                      {t.avatar}
                    </div>
                    <div className="min-w-0">
                      <div className="font-semibold text-sm text-foreground truncate">{t.name}</div>
                      <div className="text-xs text-muted-foreground truncate">{t.role}, {t.org}</div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* ── AI Detection Guide ──────────────────────────────────────────── */}
      <section className="py-16 px-4 md:px-6 bg-muted/30" id="guide">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-10">
            <Badge variant="secondary" className="mb-3 gap-1.5">
              <BookOpen className="w-3 h-3" /> Educational Resource
            </Badge>
            <h2 className="text-2xl md:text-3xl font-bold text-navy mb-3">
              Complete AI Detection Guide
            </h2>
            <p className="text-muted-foreground max-w-xl mx-auto text-pretty">
              Everything you need to understand how AI detection works, how to use it responsibly, and how to apply it across academic, publishing, SEO, and business contexts.
            </p>
          </div>
          <div className="max-w-3xl mx-auto">
            <Accordion type="single" collapsible className="space-y-2">
              {GUIDE_SECTIONS.map((section) => (
                <AccordionItem key={section.id} value={section.id} className="border border-border/50 rounded-xl overflow-hidden bg-card">
                  <AccordionTrigger className="px-5 py-4 hover:no-underline font-semibold text-foreground text-sm text-left">
                    {section.title}
                  </AccordionTrigger>
                  <AccordionContent className="px-5 pb-5">
                    <div className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line text-pretty">
                      {section.content}
                    </div>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
          {/* Internal linking in guide */}
          <div className="mt-8 max-w-3xl mx-auto p-5 bg-card border border-border/50 rounded-xl">
            <p className="text-sm text-muted-foreground leading-relaxed text-pretty">
              After detecting AI content, consider using our{' '}
              <Link to="/humanizer" className="text-primary font-semibold hover:underline">AI Humanizer</Link>{' '}
              to rewrite flagged sections, our{' '}
              <Link to="/plagiarism-checker" className="text-primary font-semibold hover:underline">Plagiarism Checker</Link>{' '}
              to verify originality, and our{' '}
              <Link to="/api" className="text-primary font-semibold hover:underline">API Platform</Link>{' '}
              to automate detection at scale.
            </p>
          </div>
        </div>
      </section>

      {/* ── FAQ ─────────────────────────────────────────────────────────── */}
      <section className="py-16 px-4 md:px-6" id="faq">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-10">
            <Badge variant="secondary" className="mb-3">FAQ</Badge>
            <h2 className="text-2xl md:text-3xl font-bold text-navy mb-3">
              Frequently Asked Questions
            </h2>
            <p className="text-muted-foreground max-w-xl mx-auto text-pretty">
              Everything you need to know about our AI detector, AI checker, and AI content detection capabilities.
            </p>
          </div>
          <div className="max-w-3xl mx-auto">
            <Accordion type="single" collapsible className="space-y-2">
              {visibleFAQs.map((faq, i) => (
                <AccordionItem key={i} value={`faq-${i}`} className="border border-border/50 rounded-xl overflow-hidden bg-card">
                  <AccordionTrigger className="px-5 py-4 hover:no-underline font-semibold text-foreground text-sm text-left">
                    {faq.q}
                  </AccordionTrigger>
                  <AccordionContent className="px-5 pb-5">
                    <p className="text-sm text-muted-foreground leading-relaxed text-pretty">{faq.a}</p>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>

            {!showAllFAQ && (
              <div className="mt-4 text-center">
                <Button
                  variant="outline"
                  onClick={() => setShowAllFAQ(true)}
                  className="gap-2"
                >
                  Show All {FAQS.length} Questions <ChevronRight className="w-4 h-4" />
                </Button>
              </div>
            )}
          </div>
        </div>
      </section>

      {/* ── EEAT / Methodology ──────────────────────────────────────────── */}
      <section className="py-16 px-4 md:px-6 bg-muted/30" id="methodology">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-10">
            <Badge variant="secondary" className="mb-3 gap-1.5">
              <Info className="w-3 h-3" /> Transparency
            </Badge>
            <h2 className="text-2xl md:text-3xl font-bold text-navy mb-3">
              Our Methodology, Standards & Commitments
            </h2>
            <p className="text-muted-foreground max-w-xl mx-auto text-pretty">
              We publish our detection methodology, version history, and ethical commitments openly. Transparency is core to trustworthy AI detection.
            </p>
            <p className="text-xs text-muted-foreground mt-2">
              Last reviewed: June 2025 · Detection Engine v4.2
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {EEAT.map((item) => {
              const Icon = item.icon;
              return (
                <Card key={item.title} className="border-border/50 h-full">
                  <CardContent className="p-6 flex flex-col gap-3 h-full">
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 bg-primary/10 rounded-lg flex items-center justify-center shrink-0">
                        <Icon className="w-4 h-4 text-primary" />
                      </div>
                      <h3 className="font-semibold text-foreground text-sm">{item.title}</h3>
                    </div>
                    <p className="text-sm text-muted-foreground leading-relaxed text-pretty">{item.desc}</p>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── Internal Links ──────────────────────────────────────────────── */}
      <section className="py-12 px-4 md:px-6 border-t border-border/50">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-base font-bold text-foreground mb-6">
            More Tools from AIDetector.cx
          </h2>
          <div className="flex flex-wrap gap-3">
            {INTERNAL_LINKS.map((link) => {
              const Icon = link.icon;
              return (
                <Link
                  key={link.href}
                  to={link.href}
                  className="flex items-center gap-2.5 px-4 py-2.5 bg-card border border-border/50 rounded-xl hover:border-primary/40 hover:bg-muted/40 transition-all group"
                >
                  <Icon className="w-4 h-4 text-primary shrink-0" />
                  <div className="min-w-0">
                    <div className="text-sm font-semibold text-foreground group-hover:text-primary transition-colors">{link.label}</div>
                    <div className="text-xs text-muted-foreground">{link.desc}</div>
                  </div>
                </Link>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── Final CTA ───────────────────────────────────────────────────── */}
      <section className="py-16 px-4 md:px-6 bg-gradient-to-br from-primary/10 via-background to-primary/5 border-t border-primary/10">
        <div className="max-w-3xl mx-auto text-center">
          <Badge variant="secondary" className="mb-4">Free — No Credit Card Required</Badge>
          <h2 className="text-2xl md:text-3xl font-bold text-navy mb-4 text-balance">
            Start Detecting AI Content Right Now
          </h2>
          <p className="text-muted-foreground mb-8 text-pretty">
            Join over 1 million students, educators, publishers, and developers who trust AIDetector.cx as their primary <strong>AI detector</strong> and <strong>AI content checker</strong>. Free to start. No credit card required.
          </p>
          <div className="flex flex-wrap gap-3 justify-center">
            <Button size="lg" className="gap-2 font-semibold" asChild>
              <a href="#detector-tool">
                <Shield className="w-4 h-4" />
                Detect AI Content Free
              </a>
            </Button>
            <Button size="lg" variant="outline" className="gap-2" asChild>
              <Link to="/pricing">
                View Pro Features <ArrowRight className="w-4 h-4" />
              </Link>
            </Button>
          </div>
          <div className="mt-6 flex flex-wrap gap-x-6 gap-y-2 justify-center">
            {[
              { icon: CheckCircle2, text: '98.7% accuracy on GPT-5.5' },
              { icon: Shield, text: 'Privacy-first — text never stored' },
              { icon: Sparkles, text: 'No credit card required' },
            ].map(({ icon: Icon, text }) => (
              <div key={text} className="flex items-center gap-1.5 text-xs text-muted-foreground">
                <Icon className="w-3.5 h-3.5 text-success" />
                {text}
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
