import { describe, it, expect } from 'vitest';
import { analyzeAdvancedText } from '../lib/detection/engine';
import { classifyWithClassifier } from '../lib/detection/classifier';
import { runEnsemble } from '../lib/detection/ensemble';

const HUMAN_WRITTEN_FALSE_POSITIVE_SAMPLE = `
What does an AI Detector actually mean?
Have you been hit by the bug yet?. You might be wondering what “the bug” in this context means, freight not, because I am about to unveil what it means, (drumroll!!!!!!!).

The influx of Artificial Intelligence has no doubt brought tremendous benefits to users across the board. However, there’s a popular saying that goes thus, too much of everything is sometimes too bad, and would consequently have its downside. With that being said, in order to curb the excessive use of artificial intelligence language models, some researchers, supervisors, and lecturers have resorted to the use of AI detectors models such as AI Detector.cx, Pangram, and ZeroGPT, amongst several others, that would help them verify if their students made use of certain AI Language models such as CHAPGPT, Gemini, and Claude 3.5 to generate their content.

On that note, it is essential that we understand what AI Detector tools actually mean and how they operate. Just like the name implies, it is a tool that is used to detect, and verify if a content was being generated fully by AI (machine generated content), or it was being generated by a mix of AI, and human intelligence, or to also detect if a content was generated by human intelligence as well. It is pertinent to note that there’s no scientific evidence to prove the result of these AI Detectors models, that’s because each detector model operates based on different methodology, statistical analysis, and several thresholds that they implore in order to give their verdict/report.

What are the parameters that most AI Detectors adopt?

From our ongoing analysis it is important that we dissect the various elements upon which an AI Detector carries out its analysis. On top of the list of elements are thresholds. Why we would be starting with thresholds is based on the various factors associated with them, which includes, sentence disparity, Burstiness, grammatical error, punctuation accuracy.

First on the list, we have sentence disparity, the case of sentence disparity is oftentimes associated with the fact that some AI detectors are regulated to understand that human writing is obscure in sentence consistency. Which is oftentimes based on the lack of coherent flow, as well as a mix of short sentences with long sentences.

The other threshold to be considered is Burstiness, which in simple terms means the volume of a particular sentence. Most AI detectors are regulated to understand that a particular volume of sentence can only be associated with machine generated content, without understanding or considering the fact that they are some professional writing writer that understands the pros and cons of writing.

The next on the list is grammatical error. This simply refers to the fact that some AI detectors are regulated to understand that the existence of grammatical errors in a content clearly indicates that such content was generated by humans, because one thing that is often associated with Artificial Intelligence is the absence of errors.

The last factor on the list, and certainly not the list is punctuation accuracy. As little as this factor seems like on the surface, it is not the same when analyzed under AI Detector. Oftentimes than not, this is not entirely an accurate verdict, because it’s important to note that some professionals, and non-English language writers have been trained judiciously, and are quite vast with the use of punctuation.

In the grand scheme of things, I sincerely do believe that the use of AI technologies has been to maximize time and efficiency, and not to tussle about which is more superior to which. I am also of the firm believe that a judicious use of AI technologies would automatically drive tremendous success in work rates.
`.trim();



const AI_CONTROL_SAMPLE = `
Artificial intelligence represents one of the most significant technological developments of the
twenty-first century. The rapid advancement of machine learning algorithms has enabled unprecedented
capabilities across numerous domains. It is important to understand that these developments carry
both transformative potential and significant risks that must be carefully managed.

In the realm of healthcare, AI-powered diagnostic tools have demonstrated remarkable accuracy in
identifying conditions ranging from diabetic retinopathy to certain forms of cancer. Moreover, drug
discovery pipelines have been substantially accelerated through the application of deep learning
models capable of predicting molecular interactions with high precision.

Furthermore, the financial sector has witnessed a fundamental transformation driven by algorithmic
trading systems and AI-powered risk assessment frameworks. It is crucial to note that these systems,
while highly efficient, require robust oversight mechanisms to prevent systemic risks. In addition,
natural language processing applications have revolutionized customer service operations across
industries.

The educational landscape is also undergoing significant change as a result of AI integration.
Personalized learning systems can now adapt to individual student needs in real time, providing
targeted support where it is most needed. It is worth noting that this shift raises important
questions about the role of human educators in an increasingly automated environment.

In conclusion, the trajectory of artificial intelligence development suggests that its impact will
continue to expand across virtually every sector of the economy. Organizations that proactively
develop AI governance frameworks and invest in workforce adaptation will be best positioned to
navigate this transformation successfully. The key is to balance innovation with responsibility,
ensuring that the benefits of AI are broadly shared while its risks are carefully mitigated.
`.trim();

describe('Balanced detector human false-positive regression', () => {
  it('does not promote the supplied human-written long-form sample to an AI-side verdict', async () => {
    const result = await analyzeAdvancedText(HUMAN_WRITTEN_FALSE_POSITIVE_SAMPLE, { contentType: 'auto' });
    const classifier = await classifyWithClassifier(HUMAN_WRITTEN_FALSE_POSITIVE_SAMPLE, 'en');

    expect(['likely-ai', 'mostly-ai-human-edited']).not.toContain(result.overall.verdict);
    expect(result.overall.aiProbability).toBeLessThan(55);
    expect(result.overall.humanProbability).toBeGreaterThan(result.overall.aiProbability);
  });

  it('preserves AI-side detection on a clear long-form AI control', async () => {
    const result = await analyzeAdvancedText(AI_CONTROL_SAMPLE, { contentType: 'auto' });
    const classifier = await classifyWithClassifier(AI_CONTROL_SAMPLE, 'en');
    console.log('Balanced AI control:', JSON.stringify({
      overall: result.overall,
      diagnostics: result.diagnostics,
      classifier: {
        aiProbability: classifier.aiProbability,
        confidence: classifier.confidence,
        classProbabilities: classifier.classProbabilities,
      },
      linguistic: result.linguisticProfile,
      statistical: result.statisticalProfile,
    }));

    expect(result.overall.aiProbability).toBeGreaterThanOrEqual(result.overall.humanProbability);
    expect(['likely-ai', 'mostly-ai-human-edited', 'mixed']).toContain(result.overall.verdict);
  });
});
