import { describe, it, expect } from 'vitest';
import { analyzeAdvancedText } from '../lib/detection/engine';
import { classifyWithClassifier } from '../lib/detection/classifier';

const HUMAN_WRITTEN_FALSE_POSITIVE_SAMPLE = `
What does an AI Detector actually mean?
Have you been hit by the bug yet?. You might be wondering what “the bug” in this context means, freight not, because I am about to unveil what it means, (drumroll!!!!!!!).

The influx of Artificial Intelligence has no doubt brought tremendous benefits to users across the board. However, there’s a popular saying that goes thus, too much of everything is sometimes too bad, and would consequently have its downside. With that being said, in order to curb the excessive use of artificial intelligence language models, some researchers, supervisors, and lecturers have resorted to the use of AI detectors models such as AI Detector.cx, Pangram, and ZeroGPT, amongst several others, that would help them verify if their students made use of certain AI Language models such as CHAPGPT, Gemini, and Claude 3.5 to generate their content.

On that note, it is essential that we understand what AI Detector tools actually mean and how they operate. Just like the name implies, it is a tool that is used to detect, and verify if a content was being generated fully by AI (machine generated content), or it was being generated by a mix of AI, and human intelligence, or to also detect if a content was generated by human intelligence as well. It is pertinent to note that there’s no scientific evidence to prove the result of these AI Detectors models, that’s because each detector model operates based on different methodology, statistical analysis, and several thresholds that they implore in order to give their verdict/report.

What are the parameters that most AI Detectors adopt?

From our ongoing analysis it is important that we dissect the various elements upon which an AI Detector carries out its analysis. On top of the list of elements are thresholds. Why we would be starting with thresholds is based on the various factors associated with them, which includes, sentence disparity, Burstiness, grammatical error, punctuation accuracy.

First on the list, we have sentence disparity, the case of sentence disparity is oftentimes associated with the fact that some AI detectors are regulated to understand that human writing is obscure in sentence consistency. Which is oftentimes based on the lack of coherent flow, as well as a mix of short sentences with long sentences.

The other threshold to be considered is Burstiness, which in simple terms means the volume of a particular sentence. Most AI detectors are regulated to understand that a particular volume of sentence can only be associated with machine generated content, without understanding or considering the fact that they are some professional writing writer that understands the pros and cons of writing.

The next on the list is grammatical error. This simply refers to the fact that some AI detectors are regulated to understand that the existence of grammatical errors in a content clearly indicates that such content was generated by humans, because one thing that is often associated with Artificial Intelligence is the absence of errors.

The last factor on the list, and certainly not the list is punctuation accuracy. As little as this factor seems like on the surface, it is not the same when analyzed under AI Detector. Oftentimes than not, this is not entirely an accurate verdict, because it’s important to note that some professionals, and non-English language writers have been trained judiciously, and are quite vast with the use of punctuation.

In the grand scheme of things, I sincerely do believe that the use of AI technologies has been to maximize time and efficiency, and not to tussle about which is more superior to which. I am also of the firm believe that a judicious use of AI technologies would automatically drive tremendous success in work rates.
`.trim();



const AI_CONTROL_SAMPLE = `
Artificial intelligence represents one of the most significant technological developments of the
twenty-first century. The rapid advancement of machine learning algorithms has enabled unprecedented
capabilities across numerous domains. It is important to understand that these developments carry
both transformative potential and significant risks that must be carefully managed.

In the realm of healthcare, AI-powered diagnostic tools have demonstrated remarkable accuracy in
identifying conditions ranging from diabetic retinopathy to certain forms of cancer. Moreover, drug
discovery pipelines have been substantially accelerated through the application of deep learning
models capable of predicting molecular interactions with high precision.

Furthermore, the financial sector has witnessed a fundamental transformation driven by algorithmic
trading systems and AI-powered risk assessment frameworks. It is crucial to note that these systems,
while highly efficient, require robust oversight mechanisms to prevent systemic risks. In addition,
natural language processing applications have revolutionized customer service operations across
industries.

The educational landscape is also undergoing significant change as a result of AI integration.
Personalized learning systems can now adapt to individual student needs in real time, providing
targeted support where it is most needed. It is worth noting that this shift raises important
questions about the role of human educators in an increasingly automated environment.

In conclusion, the trajectory of artificial intelligence development suggests that its impact will
continue to expand across virtually every sector of the economy. Organizations that proactively
develop AI governance frameworks and invest in workforce adaptation will be best positioned to
navigate this transformation successfully. The key is to balance innovation with responsibility,
ensuring that the benefits of AI are broadly shared while its risks are carefully mitigated.
`.trim();

const BROAD_CONTROLS = [
  {
    name: 'clear formulaic AI',
    expected: 'ai',
    text: `Artificial intelligence is transforming the modern workplace in profound and far-reaching ways. From automating repetitive tasks to enabling advanced data analysis, AI is reshaping how organizations operate. It is important to note that this transformation brings both opportunities and challenges. In conclusion, organizations that embrace AI-driven strategies will be well-positioned to thrive in the digital economy. Furthermore, leveraging cutting-edge technology allows businesses to achieve unprecedented levels of efficiency. It is crucial to understand that implementing AI requires careful consideration of ethical implications. As a result, companies must develop comprehensive governance frameworks to ensure responsible deployment of these powerful systems.`,
  },
  {
    name: 'natural personal human',
    expected: 'human',
    text: `I spent last Saturday fixing my old bicycle — the chain had been slipping for weeks and I'd been putting it off. Turns out the rear derailleur cable was frayed, which I only found out after an hour of confused tinkering. My neighbor Tom wandered over, took one look, and went "oh yeah, that's your cable." Embarrassing, honestly. We had tea after. He told me about his trip to Portugal where he apparently ate so much pastéis de nata that he had to buy new trousers. Classic Tom. Anyway, bike is fixed now. I celebrated with a very mediocre frozen pizza and some bad TV.`,
  },
  {
    name: 'formal academic human',
    expected: 'human-not-ai',
    text: `The relationship between synaptic plasticity and long-term memory consolidation has been a subject of sustained empirical investigation since the mid-twentieth century. Hebb's postulate, formalized in 1949, proposed that repeated co-activation of pre- and post-synaptic neurons strengthens their connection — a principle now supported by extensive electrophysiological evidence. Subsequent work by Bliss and Lømo in 1973 demonstrated long-term potentiation in the hippocampus, establishing a cellular correlate for learning. The question of whether LTP necessarily underlies all forms of declarative memory remains contested, with competing models emphasizing different molecular cascades and temporal dynamics.`,
  },
  {
    name: 'pre-AI-era style human',
    expected: 'human-not-ai',
    text: `The coffee machine in the office had been broken for three days, which, by Tuesday morning, had reduced the accounts department to a state best described as "barely functional." Karen from payroll had started bringing her own instant coffee in a thermos, which she kept locked in her desk drawer. This was discussed at length in the kitchen. Dave from IT fixed it eventually — apparently it just needed descaling, something that had apparently been on the maintenance list since 2017. The collective relief was palpable. Someone brought biscuits.`,
  },
  {
    name: 'AI lightly edited by human',
    expected: 'not-pure-human',
    text: `Artificial intelligence has emerged as a transformative force in education, raising important questions about academic integrity. Students now have access to powerful language models that can generate convincing essays in seconds — honestly, I've seen it firsthand in my own classroom. It is essential that institutions develop clear policies addressing AI use in assessments. Moreover, educators must adapt their teaching strategies to focus on critical thinking and original analysis. These changes will ensure that learning remains meaningful. But honestly, half the battle is just convincing students the skills still matter when AI can do it for them.`,
  },
  {
    name: 'human with AI polish',
    expected: 'not-pure-ai',
    text: `My grandmother kept a garden that defied all logic — rocky soil, partial shade, and the most stubborn clay this side of the county. She'd be out there every morning, muttering at the tomatoes like they might respond. They usually did, eventually. We used to sit on the back step eating warm cherry tomatoes straight off the vine, still dusty with garden soil. That taste is something I can't quite recreate, no matter how good the supermarket variety is. In conclusion, the significance of intergenerational knowledge transfer in horticultural practices cannot be overstated. Furthermore, the preservation of traditional gardening methods represents an important cultural heritage that deserves recognition and documentation.`,
  },
  {
    name: 'true mixed authorship',
    expected: 'not-pure',
    text: `Last week I tried making sourdough bread for the first time. Total disaster. The starter smelled wrong, the dough wouldn't hold its shape, and what came out of the oven could have been used as a doorstop. My flatmate said it tasted "interesting" which we both knew meant inedible. Sourdough bread represents a significant intersection of traditional fermentation techniques and modern culinary science. The biochemical processes involved in lactic acid fermentation contribute to both the distinctive flavor profile and the improved nutritional characteristics of the final product. It is important to note that consistent temperature control is essential for successful fermentation. Furthermore, the hydration ratio of the dough plays a crucial role in determining crumb structure and crust development.`,
  },
] as const;

describe('Balanced detector human false-positive regression', () => {
  it('does not promote the supplied human-written long-form sample to an AI-side verdict', async () => {
    const result = await analyzeAdvancedText(HUMAN_WRITTEN_FALSE_POSITIVE_SAMPLE, { contentType: 'auto' });
    expect(['likely-ai', 'mostly-ai-human-edited']).not.toContain(result.overall.verdict);
    expect(result.overall.aiProbability).toBeLessThan(55);
    expect(result.overall.humanProbability).toBeGreaterThan(result.overall.aiProbability);
  });

  it('preserves AI-side detection on a clear long-form AI control', async () => {
    const result = await analyzeAdvancedText(AI_CONTROL_SAMPLE, { contentType: 'auto' });
    const classifier = await classifyWithClassifier(AI_CONTROL_SAMPLE, 'en');
    expect(result.overall.aiProbability).toBeGreaterThanOrEqual(result.overall.humanProbability);
    expect(['likely-ai', 'mostly-ai-human-edited', 'mixed']).toContain(result.overall.verdict);
  });

  for (const sample of BROAD_CONTROLS) {
    it(`broad regression: ${sample.name}`, async () => {
      const result = await analyzeAdvancedText(sample.text, { contentType: 'auto' });
      const classifier = await classifyWithClassifier(sample.text, 'en');
      console.log('Balanced broad control:', sample.name, JSON.stringify({
        overall: result.overall,
        classifier: {
          aiProbability: classifier.aiProbability,
          confidence: classifier.confidence,
          classProbabilities: classifier.classProbabilities,
        },
        linguistic: result.linguisticProfile,
        statistical: result.statisticalProfile,
        diagnostics: result.diagnostics,
      }));

      if (sample.expected === 'ai') {
        expect(result.overall.aiProbability).toBeGreaterThanOrEqual(result.overall.humanProbability);
        expect(['likely-ai', 'mostly-ai-human-edited', 'mixed']).toContain(result.overall.verdict);
      } else if (sample.expected === 'human') {
        expect(result.overall.humanProbability).toBeGreaterThanOrEqual(result.overall.aiProbability);
        expect(['likely-human', 'mostly-human-ai-assisted', 'mixed', 'inconclusive']).toContain(result.overall.verdict);
      } else if (sample.expected === 'human-not-ai') {
        expect(['likely-ai', 'mostly-ai-human-edited']).not.toContain(result.overall.verdict);
      } else if (sample.expected === 'not-pure-human') {
        expect(result.overall.verdict).not.toBe('likely-human');
      } else if (sample.expected === 'not-pure-ai') {
        expect(result.overall.verdict).not.toBe('likely-ai');
      } else {
        expect(['likely-ai', 'likely-human']).not.toContain(result.overall.verdict);
      }
    });
  }
});
