import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

async function callGemini(prompt: string, apiKey: string) {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent`;
  const response = await fetch(url, {
    method: 'POST',
    headers: { 
      'Content-Type': 'application/json',
      'x-goog-api-key': apiKey
    },
    body: JSON.stringify({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      generationConfig: {
        temperature: 0.2,
      }
    })
  });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error?.message || 'Gemini API Error');
  return data.candidates?.[0]?.content?.parts?.[0]?.text || '';
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get('Authorization')!;
    if (!authHeader) throw new Error('Missing Authorization header');

    const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? '';
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';
    const supabaseClient = createClient(supabaseUrl, supabaseServiceKey);

    const token = authHeader.replace('Bearer ', '').trim();
    let user;
    let isDirectKey = false;
    if (token.startsWith('aid_')) {
      const { data: keyData, error: keyError } = await supabaseClient.from('api_keys').select('user_id').eq('api_key', token).single();
      if (keyError || !keyData) throw new Error('Unauthorized');
      user = { id: keyData.user_id };
      supabaseClient.from('api_keys').update({ last_used_at: new Date().toISOString() }).eq('api_key', token).then();
    } else if (!token.startsWith('eyJ')) {
      user = { id: 'direct_key_user' };
      isDirectKey = true;
    } else {
      const { data: { user: authUser }, error: authError } = await supabaseClient.auth.getUser(token);
      if (authError || !authUser) throw new Error('Unauthorized');
      user = authUser;
    }

    const { text, type } = await req.json();

    if (!text && type === 'text') {
      return new Response(JSON.stringify({ error: 'Text is required' }), { status: 400, headers: corsHeaders });
    }

    let systemKeys: Record<string, string> = {};
    try {
      const { data } = await supabaseClient.from('system_api_keys').select('provider, key_value').eq('status', 'active');
      if (data) data.forEach(k => { systemKeys[k.provider] = k.key_value; });
    } catch (e) {}

    let geminiKey = isDirectKey && !token.startsWith('sk-') ? token : (systemKeys['gemini'] || Deno.env.get('GEMINI_API_KEY') || Deno.env.get('INTEGRATIONS_API_KEY'));
    let openAIKey = token.startsWith('sk-') ? token : (systemKeys['openai'] || Deno.env.get('OPENAI_API_KEY'));
    
    if (!geminiKey && !openAIKey) {
      return new Response(JSON.stringify({ 
        success: false, 
        message: 'API Key not configured in admin. Please connect Gemini in the dashboard.',
        aiProbability: 0,
        riskLevel: 'Unknown'
      }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }

    if (type === 'text') {
      const prompt = `You are an expert AI detection system. Analyze the following text and determine the probability that it was generated by AI.
Also provide a confidence score, risk level (Low, Medium, High, Critical), perplexity score (0-100), and burstiness score (0-100).
Return ONLY a valid JSON object with the following keys:
- aiProbability (0-100)
- confidenceScore (0-100)
- riskLevel (Low, Medium, High, Critical)
- perplexityScore (0-100)
- burstinessScore (0-100)
- humanEvidence (array of strings, e.g., ["Personal anecdote", "Emotional language"])
- aiEvidence (array of strings, e.g., ["Repetitive sentence structure", "Robotic tone"])

Text: ${text.substring(0, 5000)}
`;

      let responseText = '';
      if (token.startsWith('sk-')) {
         const res = await fetch('https://api.openai.com/v1/chat/completions', {
           method: 'POST',
           headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${openAIKey}` },
           body: JSON.stringify({
             model: 'gpt-4o-mini',
             messages: [{ role: 'user', content: prompt }],
             temperature: 0.2
           })
         });
         const data = await res.json();
         if (!res.ok) throw new Error(data.error?.message || 'OpenAI API Error');
         responseText = data.choices?.[0]?.message?.content || '';
      } else {
         responseText = await callGemini(prompt, geminiKey);
      }
      
      // Extract JSON from the response text
      const match = responseText.match(/\{[\s\S]*\}/);
      let resultData;
      if (match) {
        try {
          resultData = JSON.parse(match[0]);
        } catch (e) {
          resultData = null;
        }
      }

      if (!resultData) {
        throw new Error('Failed to parse detection result');
      }

      const sentences = text.split(/[.!?]+/).filter(Boolean);
      
      return new Response(JSON.stringify({
        success: true,
        aiProbability: resultData.aiProbability || 0,
        confidenceScore: resultData.confidenceScore || 0,
        riskLevel: resultData.riskLevel || 'Low',
        sentences: sentences.map((s: string) => ({
          text: s.trim(),
          aiProbability: resultData.aiProbability || 0, // Simplified: apply general probability
          perplexityScore: resultData.perplexityScore || 0,
          burstinessScore: resultData.burstinessScore || 0,
        })),
        paragraphTimeline: [{ aiProbability: resultData.aiProbability || 0 }],
        humanEvidence: { score: 100 - (resultData.aiProbability || 0), indicators: resultData.humanEvidence || [] },
        aiEvidence: { score: resultData.aiProbability || 0, indicators: resultData.aiEvidence || [] }
      }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    return new Response(JSON.stringify({ error: 'Unsupported detection type' }), { status: 400, headers: corsHeaders });
  } catch (error: any) {
    return new Response(JSON.stringify({ message: error.message }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});