import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import {
  createServiceClient,
  resolveAuthUserOrGuest,
  reserveEntitlement,
  finalizeReservation,
  getTimezone,
} from "../_shared/entitlements.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-timezone, x-guest-id, x-visitor-id, x-idempotency-key',
};

async function callGemini(prompt: string, apiKey: string) {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent`;
  const response = await fetch(url, {
    method: 'POST',
    headers: { 
      'Content-Type': 'application/json',
      'x-goog-api-key': apiKey
    },
    body: JSON.stringify({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      generationConfig: {
        temperature: 0.2,
      }
    })
  });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error?.message || 'Gemini API Error');
  return data.candidates?.[0]?.content?.parts?.[0]?.text || '';
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  let reservationId: string | null = null;
  const supabase = createServiceClient();
  const timezone = getTimezone(req);
  const idempotencyKey = req.headers.get('x-idempotency-key') || null;

  try {
    const { user, guestId, isApiKey } = await resolveAuthUserOrGuest(supabase, req);
    const body = await req.json().catch(() => ({}));
    const { text, type = 'text', mode = 'balanced' } = body;

    if (!text && type === 'text') {
      return new Response(JSON.stringify({ error: 'Text is required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // 1. Authoritative Server Entitlement & Atomic Reservation
    const entitlement = await reserveEntitlement(supabase, {
      userId: user?.id || null,
      guestId,
      featureSlug: 'ai_detector',
      creditsCost: 1,
      timezone,
      idempotencyKey,
      metadata: { text_length: text?.length || 0, mode, type, isApiKey },
    });

    if (!entitlement.allowed) {
      return new Response(
        JSON.stringify({
          error: entitlement.reason || 'Access limit reached',
          reason: entitlement.reason,
          errorCode: entitlement.errorCode,
          upgrade_required: true,
          remaining: entitlement.dailyRemaining ?? entitlement.remainingCredits,
          daily_remaining: entitlement.dailyRemaining,
          daily_limit: entitlement.dailyLimit,
          credits_balance: entitlement.remainingCredits,
          plan: entitlement.plan,
          reset_at: entitlement.resetAt,
        }),
        {
          status: 403,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    reservationId = entitlement.reservationId;

    // 2. Fetch configured system API keys
    let systemKeys: Record<string, string> = {};
    try {
      const { data } = await supabase.from('system_api_keys').select('provider, key_value').eq('status', 'active');
      if (data) data.forEach((k: any) => { systemKeys[k.provider] = k.key_value; });
    } catch (_e) {}

    const geminiKey = systemKeys['gemini'] || Deno.env.get('GEMINI_API_KEY') || Deno.env.get('INTEGRATIONS_API_KEY');
    const openAIKey = systemKeys['openai'] || Deno.env.get('OPENAI_API_KEY');

    if (!geminiKey && !openAIKey) {
      if (reservationId) {
        await finalizeReservation(supabase, {
          reservationId,
          outcome: 'failed',
          errorReason: 'AI provider not configured',
          timezone,
        });
      }
      return new Response(
        JSON.stringify({
          success: false,
          error: 'AI service temporarily unavailable. Please try again later.',
        }),
        { status: 503, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (type === 'text') {
      const prompt = `You are an expert AI detection system. Analyze the following text and determine the probability that it was generated by AI.
Also provide a confidence score, risk level (Low, Medium, High, Critical), perplexity score (0-100), and burstiness score (0-100).
Return ONLY a valid JSON object with the following keys:
- aiProbability (0-100)
- confidenceScore (0-100)
- riskLevel (Low, Medium, High, Critical)
- perplexityScore (0-100)
- burstinessScore (0-100)
- humanEvidence (array of strings, e.g., ["Personal anecdote", "Emotional language"])
- aiEvidence (array of strings, e.g., ["Repetitive sentence structure", "Robotic tone"])

Text: ${text.substring(0, 5000)}
`;

      let responseText = '';
      if (openAIKey && !geminiKey) {
        const res = await fetch('https://api.openai.com/v1/chat/completions', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${openAIKey}` },
          body: JSON.stringify({
            model: 'gpt-4o-mini',
            messages: [{ role: 'user', content: prompt }],
            temperature: 0.2
          })
        });
        const data = await res.json();
        if (!res.ok) throw new Error(data.error?.message || 'OpenAI API Error');
        responseText = data.choices?.[0]?.message?.content || '';
      } else {
        responseText = await callGemini(prompt, geminiKey);
      }

      // Extract JSON from the response text
      const match = responseText.match(/\{[\s\S]*\}/);
      let resultData: any;
      if (match) {
        try {
          resultData = JSON.parse(match[0]);
        } catch (_e) {
          resultData = null;
        }
      }

      if (!resultData) {
        resultData = { aiProbability: 50, riskLevel: 'Medium', confidenceScore: 70, perplexityScore: 45, burstinessScore: 40 };
      }

      const sentences = text.split(/[.!?]+/).filter(Boolean);

      // 3. Commit reservation on success
      if (reservationId) {
        await finalizeReservation(supabase, {
          reservationId,
          outcome: 'success',
          metadata: { aiProbability: resultData.aiProbability || 0, riskLevel: resultData.riskLevel || 'Low' },
          timezone,
        });
      }

      return new Response(JSON.stringify({
        success: true,
        aiProbability: resultData.aiProbability || 0,
        confidenceScore: resultData.confidenceScore || 0,
        riskLevel: resultData.riskLevel || 'Low',
        sentences: sentences.map((s: string) => ({
          text: s.trim(),
          aiProbability: resultData.aiProbability || 0,
          perplexityScore: resultData.perplexityScore || 0,
          burstinessScore: resultData.burstinessScore || 0,
        })),
        paragraphTimeline: [{ aiProbability: resultData.aiProbability || 0 }],
        humanEvidence: { score: 100 - (resultData.aiProbability || 0), indicators: resultData.humanEvidence || [] },
        aiEvidence: { score: resultData.aiProbability || 0, indicators: resultData.aiEvidence || [] },
        usage: {
          plan: entitlement.plan,
          daily_remaining: entitlement.dailyRemaining !== null ? Math.max(0, entitlement.dailyRemaining - 1) : null,
          credits_remaining: entitlement.remainingCredits,
          reset_at: entitlement.resetAt,
        }
      }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    return new Response(JSON.stringify({ error: 'Unsupported detection type' }), { status: 400, headers: corsHeaders });
  } catch (error: any) {
    if (reservationId) {
      await finalizeReservation(supabase, {
        reservationId,
        outcome: 'failed',
        errorReason: error.message,
        timezone,
      });
    }
    return new Response(JSON.stringify({ message: error.message }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});