import { serve } from "https://deno.land/std/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { text } = await req.json();
    if (!text) {
      throw new Error('Text is required');
    }

    const apiKey = Deno.env.get('INTEGRATIONS_API_KEY');
    if (!apiKey) {
      throw new Error('Server configuration error (missing key)');
    }

    const systemPrompt = `You are an advanced AI text detection engine. Your task is to analyze the provided text and determine if it was written by a human or generated by an AI model (like ChatGPT, Claude, Gemini, etc.).
Analyze the text at the paragraph and sentence level. Consider perplexity, burstiness, pattern repetitiveness, emotional language, personal anecdotes, and overall flow.

You MUST respond strictly with a valid JSON object matching this schema (do NOT wrap it in Markdown \`\`\`json ... \`\`\` tags, just output the raw JSON object):
{
  "aiProbability": number, // 0-100
  "confidenceScore": number, // 0-100
  "riskLevel": "High" | "Medium" | "Low" | "Critical",
  "paragraphTimeline": [
    { "aiProbability": number } // 0-100 for each paragraph
  ],
  "sentences": [
    {
      "text": "The sentence text.",
      "aiProbability": number, // 0-100
      "perplexityScore": number,
      "burstinessScore": number
    }
  ],
  "humanEvidence": {
    "score": number, // 0-100
    "indicators": ["List of indicators like 'emotional language', 'personal anecdote', 'unique phrasing'"]
  },
  "fingerprint": {
    "primaryModel": "ChatGPT" | "Claude" | "Gemini" | "Human" | "Unknown",
    "primaryConfidence": number,
    "secondaryModel": "string or omit",
    "secondaryConfidence": number
  }
}

Text to analyze:
"""
${text}
"""`;

    // We will use the large language model endpoint but without streaming to keep things simple for JSON parsing
    // Wait, the documentation says: POST .../v1beta/models/gemini-2.5-flash:generateContent
    // Let's see if generateContent works (non-streaming).
    const upstream = await fetch(
      "https://app-c18l1vf2nz7l-api-VaOwP8E7dJqa.gateway.appmedo.com/v1beta/models/gemini-2.5-flash:generateContent",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-Gateway-Authorization": `Bearer ${apiKey}`,
        },
        body: JSON.stringify({
          contents: [{ role: "user", parts: [{ text: systemPrompt }] }],
          generationConfig: {
            responseMimeType: "application/json"
          }
        }),
      }
    );

    if (!upstream.ok) {
      const errText = await upstream.text();
      // Fallback to streamGenerateContent if generateContent is not supported by gateway
      if (upstream.status === 404 || upstream.status === 500) {
        console.error("Non-stream failed, falling back to streamGenerateContent", errText);
      } else {
         throw new Error(`Upstream API failed: ${upstream.status} ${errText}`);
      }
    }

    let resultJson = null;
    if (upstream.ok) {
       const resData = await upstream.json();
       const rawText = resData.candidates?.[0]?.content?.parts?.[0]?.text || "{}";
       try {
         resultJson = JSON.parse(rawText.replace(/^```json\n|\n```$/g, ''));
       } catch(e) {
         console.error("Failed to parse JSON:", rawText);
         throw e;
       }
    } else {
       // Fallback to streaming endpoint if non-streaming not allowed
       const fallbackUpstream = await fetch(
          "https://app-c18l1vf2nz7l-api-VaOwP8E7dJqa.gateway.appmedo.com/v1beta/models/gemini-2.5-flash:streamGenerateContent?alt=sse",
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "X-Gateway-Authorization": `Bearer ${apiKey}`,
            },
            body: JSON.stringify({
              contents: [{ role: "user", parts: [{ text: systemPrompt }] }],
            }),
          }
        );
        if (!fallbackUpstream.ok) throw new Error("Fallback upstream failed");
        
        const reader = fallbackUpstream.body?.getReader();
        const decoder = new TextDecoder();
        let fullText = "";
        let buffer = "";
        if (reader) {
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            buffer += decoder.decode(value, { stream: true });
            const lines = buffer.split('\n');
            buffer = lines.pop() || '';
            for (const line of lines) {
              if (line.startsWith('data: ') && line !== 'data: [DONE]') {
                try {
                   const data = JSON.parse(line.slice(5));
                   if (data.candidates?.[0]?.content?.parts?.[0]?.text) {
                     fullText += data.candidates[0].content.parts[0].text;
                   }
                } catch(e) {}
              }
            }
          }
        }
        
        try {
           const cleanText = fullText.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
           resultJson = JSON.parse(cleanText);
        } catch(e) {
           throw new Error("Failed to parse JSON from stream: " + fullText);
        }
    }

    return new Response(JSON.stringify(resultJson), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error: any) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});