import {
  Customer360Profile,
  DateRangePreset,
  FunnelStageData,
  JourneyEvent,
  OverviewMetricsSummary,
  PageAnalyticsItem,
  NavigationPathItem,
  ToolIntelligenceItem,
  AcquisitionReportItem,
  TrafficChannel,
} from '@/types/customerIntelligence';
import { maskIpAddress } from './visitorTracking';

export const TOOLS_ROSTER = [
  { id: 'ai_detector', name: 'AI Detector', icon: 'ShieldCheck' },
  { id: 'plagiarism_checker', name: 'Plagiarism Checker', icon: 'FileSearch' },
  { id: 'humanizer', name: 'Humanizer', icon: 'Sparkles' },
  { id: 'seo_assistant', name: 'SEO Assistant', icon: 'Search' },
  { id: 'image_detector', name: 'AI Image Detector', icon: 'Image' },
  { id: 'video_detector', name: 'AI Video Detector', icon: 'Video' },
  { id: 'summarizer', name: 'AI Summarizer', icon: 'FileText' },
  { id: 'word_counter', name: 'Word Counter', icon: 'Type' },
];

/**
 * Generate a comprehensive, realistic seed dataset of Customer 360 Profiles
 * for accurate dashboard analytics, funnel exploration, and customer drawer testing.
 */
export function generateSeedCustomers(): Customer360Profile[] {
  return [
    {
      identity: {
        visitorId: 'v_89123_89acbf1',
        userId: 'u_usr_sarah_jenkins',
        email: 'sarah.jenkins@stanford.edu',
        fullName: 'Dr. Sarah Jenkins',
        isRegistered: true,
        subscriptionPlan: 'pro',
        customerSince: '2025-01-14T09:30:00Z',
        firstSeen: '2025-01-10T14:22:00Z',
        lastSeen: '2025-02-18T16:45:00Z',
        status: 'Active',
      },
      location: {
        country: 'United States',
        region: 'California',
        city: 'Palo Alto',
        timezone: 'America/Los_Angeles',
        ipAuthorizedMasked: maskIpAddress('172.56.21.89'),
      },
      acquisition: {
        firstSource: 'Google Search',
        firstChannel: 'organic',
        latestSource: 'Direct',
        latestChannel: 'direct',
        firstReferrer: 'https://www.google.com/search?q=best+ai+text+detector+academic',
        landingPage: '/ai-detector',
        utm: { utm_source: 'google', utm_medium: 'organic' },
      },
      device: {
        category: 'desktop',
        browser: 'Google Chrome 124',
        os: 'macOS Sonoma',
        language: 'en-US',
        screenResolution: '2560x1440',
      },
      engagement: {
        totalSessions: 18,
        totalPageViews: 84,
        totalEngagedTimeSeconds: 4320,
        avgSessionDurationSeconds: 240,
        lastActivity: '2025-02-18T16:45:00Z',
        toolsUsed: [
          { tool: 'AI Detector', count: 42 },
          { tool: 'Plagiarism Checker', count: 19 },
          { tool: 'SEO Assistant', count: 4 },
        ],
        totalScansPerformed: 65,
        engagementScore: 92,
      },
      conversion: {
        registrationStatus: 'verified',
        pricingPageViews: 5,
        checkoutAttempts: 1,
        selectedPlan: 'Pro Plan ($19/mo)',
        subscriptionStatus: 'active',
        lifetimeRevenue: 57.0,
        conversionStatus: 'paid_customer',
      },
      timeline: [
        { id: 'e1', visitorId: 'v_89123_89acbf1', sessionId: 's1', eventType: 'page_view', page: '/ai-detector', timestamp: '2025-01-10T14:22:00Z' },
        { id: 'e2', visitorId: 'v_89123_89acbf1', sessionId: 's1', eventType: 'scan_started', toolName: 'AI Detector', timestamp: '2025-01-10T14:23:10Z' },
        { id: 'e3', visitorId: 'v_89123_89acbf1', sessionId: 's1', eventType: 'result_viewed', toolName: 'AI Detector', timestamp: '2025-01-10T14:23:45Z' },
        { id: 'e4', visitorId: 'v_89123_89acbf1', sessionId: 's1', eventType: 'registration_prompt_viewed', timestamp: '2025-01-10T14:24:10Z' },
        { id: 'e5', visitorId: 'v_89123_89acbf1', sessionId: 's1', eventType: 'registration_started', timestamp: '2025-01-10T14:24:30Z' },
        { id: 'e6', visitorId: 'v_89123_89acbf1', sessionId: 's1', eventType: 'registration_completed', userId: 'u_usr_sarah_jenkins', timestamp: '2025-01-10T14:25:20Z' },
        { id: 'e7', visitorId: 'v_89123_89acbf1', sessionId: 's2', eventType: 'pricing_viewed', page: '/pricing', timestamp: '2025-01-14T09:28:00Z' },
        { id: 'e8', visitorId: 'v_89123_89acbf1', sessionId: 's2', eventType: 'plan_selected', planName: 'Pro', timestamp: '2025-01-14T09:29:15Z' },
        { id: 'e9', visitorId: 'v_89123_89acbf1', sessionId: 's2', eventType: 'checkout_started', planName: 'Pro', timestamp: '2025-01-14T09:29:40Z' },
        { id: 'e10', visitorId: 'v_89123_89acbf1', sessionId: 's2', eventType: 'checkout_completed', planName: 'Pro', timestamp: '2025-01-14T09:30:00Z' },
      ],
      segments: [{ id: 'seg_high_value', name: 'High-Value Academic', description: 'Faculty & University researchers', is_system: true, is_dynamic: true, rules_json: {}, created_at: '', updated_at: '' }],
      tags: [{ id: 'tag_edu', name: 'Higher Ed', color: '#8B5CF6', is_system: false, created_at: '' }],
    },
    {
      identity: {
        visitorId: 'v_44901_387dca2',
        userId: 'u_usr_marcus_vance',
        email: 'marcus@growthscale.agency',
        fullName: 'Marcus Vance',
        isRegistered: true,
        subscriptionPlan: 'business',
        customerSince: '2025-01-08T11:15:00Z',
        firstSeen: '2025-01-05T08:12:00Z',
        lastSeen: '2025-02-18T18:10:00Z',
        status: 'Active',
      },
      location: {
        country: 'United Kingdom',
        region: 'England',
        city: 'London',
        timezone: 'Europe/London',
        ipAuthorizedMasked: maskIpAddress('82.165.197.102'),
      },
      acquisition: {
        firstSource: 'LinkedIn Campaign',
        firstChannel: 'paid',
        latestSource: 'Direct',
        latestChannel: 'direct',
        firstReferrer: 'https://www.linkedin.com/feed/',
        landingPage: '/ai-checker-for-bloggers',
        utm: { utm_source: 'linkedin_ads', utm_medium: 'cpc', utm_campaign: 'q1_content_agencies' },
      },
      device: {
        category: 'desktop',
        browser: 'Google Chrome 123',
        os: 'Windows 11',
        language: 'en-GB',
        screenResolution: '1920x1080',
      },
      engagement: {
        totalSessions: 32,
        totalPageViews: 148,
        totalEngagedTimeSeconds: 8640,
        avgSessionDurationSeconds: 270,
        lastActivity: '2025-02-18T18:10:00Z',
        toolsUsed: [
          { tool: 'SEO Assistant', count: 56 },
          { tool: 'AI Detector', count: 38 },
          { tool: 'Humanizer', count: 24 },
        ],
        totalScansPerformed: 118,
        engagementScore: 98,
      },
      conversion: {
        registrationStatus: 'verified',
        pricingPageViews: 8,
        checkoutAttempts: 2,
        selectedPlan: 'Business Plan ($49/mo)',
        subscriptionStatus: 'active',
        lifetimeRevenue: 98.0,
        conversionStatus: 'paid_customer',
      },
      timeline: [
        { id: 'm1', visitorId: 'v_44901_387dca2', sessionId: 'ms1', eventType: 'page_view', page: '/ai-checker-for-bloggers', timestamp: '2025-01-05T08:12:00Z' },
        { id: 'm2', visitorId: 'v_44901_387dca2', sessionId: 'ms1', eventType: 'tool_opened', toolName: 'SEO Assistant', timestamp: '2025-01-05T08:13:00Z' },
        { id: 'm3', visitorId: 'v_44901_387dca2', sessionId: 'ms1', eventType: 'scan_started', toolName: 'SEO Assistant', timestamp: '2025-01-05T08:14:20Z' },
        { id: 'm4', visitorId: 'v_44901_387dca2', sessionId: 'ms1', eventType: 'result_viewed', toolName: 'SEO Assistant', timestamp: '2025-01-05T08:14:50Z' },
        { id: 'm5', visitorId: 'v_44901_387dca2', sessionId: 'ms1', eventType: 'pricing_viewed', page: '/pricing', timestamp: '2025-01-08T11:10:00Z' },
        { id: 'm6', visitorId: 'v_44901_387dca2', sessionId: 'ms1', eventType: 'checkout_started', planName: 'Business', timestamp: '2025-01-08T11:13:30Z' },
        { id: 'm7', visitorId: 'v_44901_387dca2', sessionId: 'ms1', eventType: 'checkout_completed', planName: 'Business', timestamp: '2025-01-08T11:15:00Z' },
      ],
      segments: [{ id: 'seg_agency', name: 'SEO & Content Agencies', description: 'High volume publishing teams', is_system: false, is_dynamic: true, rules_json: {}, created_at: '', updated_at: '' }],
      tags: [{ id: 'tag_biz', name: 'Agency Partner', color: '#3B82F6', is_system: false, created_at: '' }],
    },
    {
      identity: {
        visitorId: 'v_12894_99211aa',
        userId: null,
        email: null,
        fullName: null,
        isRegistered: false,
        subscriptionPlan: 'free',
        customerSince: null,
        firstSeen: '2025-02-18T10:04:00Z',
        lastSeen: '2025-02-18T10:18:00Z',
        status: 'Anonymous Guest',
      },
      location: {
        country: 'Germany',
        region: 'Bavaria',
        city: 'Munich',
        timezone: 'Europe/Berlin',
        ipAuthorizedMasked: maskIpAddress('141.84.22.45'),
      },
      acquisition: {
        firstSource: 'Reddit',
        firstChannel: 'social',
        latestSource: 'Reddit',
        latestChannel: 'social',
        firstReferrer: 'https://www.reddit.com/r/ArtificialInteligence/comments/ai_detection_tools/',
        landingPage: '/ai-detector',
        utm: { utm_source: 'reddit', utm_medium: 'social' },
      },
      device: {
        category: 'mobile',
        browser: 'Safari Mobile 17',
        os: 'iOS 17.3',
        language: 'de-DE',
        screenResolution: '390x844',
      },
      engagement: {
        totalSessions: 1,
        totalPageViews: 4,
        totalEngagedTimeSeconds: 420,
        avgSessionDurationSeconds: 420,
        lastActivity: '2025-02-18T10:18:00Z',
        toolsUsed: [
          { tool: 'AI Detector', count: 1 },
          { tool: 'Humanizer', count: 1 },
        ],
        totalScansPerformed: 2,
        engagementScore: 45,
      },
      conversion: {
        registrationStatus: 'anonymous',
        pricingPageViews: 1,
        checkoutAttempts: 1,
        selectedPlan: 'Pro Plan',
        subscriptionStatus: 'none',
        lifetimeRevenue: 0,
        conversionStatus: 'lead',
      },
      timeline: [
        { id: 'g1', visitorId: 'v_12894_99211aa', sessionId: 'gs1', eventType: 'page_view', page: '/ai-detector', timestamp: '2025-02-18T10:04:00Z' },
        { id: 'g2', visitorId: 'v_12894_99211aa', sessionId: 'gs1', eventType: 'scan_started', toolName: 'AI Detector', timestamp: '2025-02-18T10:05:15Z' },
        { id: 'g3', visitorId: 'v_12894_99211aa', sessionId: 'gs1', eventType: 'result_viewed', toolName: 'AI Detector', timestamp: '2025-02-18T10:05:40Z' },
        { id: 'g4', visitorId: 'v_12894_99211aa', sessionId: 'gs1', eventType: 'page_view', page: '/humanizer', timestamp: '2025-02-18T10:07:00Z' },
        { id: 'g5', visitorId: 'v_12894_99211aa', sessionId: 'gs1', eventType: 'pricing_viewed', page: '/pricing', timestamp: '2025-02-18T10:14:00Z' },
        { id: 'g6', visitorId: 'v_12894_99211aa', sessionId: 'gs1', eventType: 'plan_selected', planName: 'Pro', timestamp: '2025-02-18T10:15:20Z' },
        { id: 'g7', visitorId: 'v_12894_99211aa', sessionId: 'gs1', eventType: 'checkout_started', planName: 'Pro', timestamp: '2025-02-18T10:16:00Z' },
        { id: 'g8', visitorId: 'v_12894_99211aa', sessionId: 'gs1', eventType: 'checkout_abandoned', planName: 'Pro', timestamp: '2025-02-18T10:18:00Z' },
      ],
      segments: [],
      tags: [{ id: 'tag_checkout_drop', name: 'Checkout Dropoff', color: '#F59E0B', is_system: true, created_at: '' }],
    },
    {
      identity: {
        visitorId: 'v_77209_1109aab',
        userId: 'u_usr_elena_rostova',
        email: 'elena.rostova@mediavision.co',
        fullName: 'Elena Rostova',
        isRegistered: true,
        subscriptionPlan: 'free',
        customerSince: '2025-02-12T14:00:00Z',
        firstSeen: '2025-02-10T11:40:00Z',
        lastSeen: '2025-02-18T15:20:00Z',
        status: 'Registered Free',
      },
      location: {
        country: 'Canada',
        region: 'Ontario',
        city: 'Toronto',
        timezone: 'America/Toronto',
        ipAuthorizedMasked: maskIpAddress('142.250.190.46'),
      },
      acquisition: {
        firstSource: 'Google Search',
        firstChannel: 'organic',
        latestSource: 'Direct',
        latestChannel: 'direct',
        firstReferrer: 'https://www.google.com/search?q=free+ai+summarizer+bullet+points',
        landingPage: '/ai-summarizer',
        utm: { utm_source: 'google', utm_medium: 'organic' },
      },
      device: {
        category: 'desktop',
        browser: 'Mozilla Firefox 122',
        os: 'macOS Ventura',
        language: 'en-CA',
        screenResolution: '1680x1050',
      },
      engagement: {
        totalSessions: 6,
        totalPageViews: 22,
        totalEngagedTimeSeconds: 1680,
        avgSessionDurationSeconds: 280,
        lastActivity: '2025-02-18T15:20:00Z',
        toolsUsed: [
          { tool: 'AI Summarizer', count: 12 },
          { tool: 'Word Counter', count: 6 },
          { tool: 'AI Detector', count: 4 },
        ],
        totalScansPerformed: 22,
        engagementScore: 68,
      },
      conversion: {
        registrationStatus: 'registered',
        pricingPageViews: 2,
        checkoutAttempts: 0,
        selectedPlan: 'Free Plan',
        subscriptionStatus: 'free',
        lifetimeRevenue: 0,
        conversionStatus: 'lead',
      },
      timeline: [
        { id: 'el1', visitorId: 'v_77209_1109aab', sessionId: 'els1', eventType: 'page_view', page: '/ai-summarizer', timestamp: '2025-02-10T11:40:00Z' },
        { id: 'el2', visitorId: 'v_77209_1109aab', sessionId: 'els1', eventType: 'tool_opened', toolName: 'AI Summarizer', timestamp: '2025-02-10T11:41:00Z' },
        { id: 'el3', visitorId: 'v_77209_1109aab', sessionId: 'els1', eventType: 'registration_started', timestamp: '2025-02-12T13:58:00Z' },
        { id: 'el4', visitorId: 'v_77209_1109aab', sessionId: 'els1', eventType: 'registration_completed', userId: 'u_usr_elena_rostova', timestamp: '2025-02-12T14:00:00Z' },
        { id: 'el5', visitorId: 'v_77209_1109aab', sessionId: 'els2', eventType: 'pricing_viewed', page: '/pricing', timestamp: '2025-02-18T15:18:00Z' },
      ],
      segments: [],
      tags: [{ id: 'tag_free_active', name: 'Active Free User', color: '#10B981', is_system: false, created_at: '' }],
    },
  ];
}
