import { useState, lazy, Suspense } from 'react';
import { Link } from 'react-router-dom';
import MainLayout from '@/components/layouts/MainLayout';
import PageMeta from '@/components/common/PageMeta';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  FileText, ImageIcon, Video, ScanFace, ClipboardList,
  TextSearch, Quote, ShieldAlert, Mic, Activity,
  Shield, CheckCircle2, Zap, Globe, Upload, Lock
} from 'lucide-react';
import AITextDetector from './detector/AITextDetector';
import AIImageDetector from './detector/AIImageDetector';
import AIVideoDetector from './detector/AIVideoDetector';
import DeepfakeImageDetector from './detector/DeepfakeImageDetector';
import DeepfakeVideoDetector from './detector/DeepfakeVideoDetector';
import AIVoiceDetector from './detector/AIVoiceDetector';
import PlagiarismDetector from './detector/PlagiarismDetector';
import HallucinationDetector from './detector/HallucinationDetector';
import CitationVerifier from './detector/CitationVerifier';
import WritingMonitor from './detector/WritingMonitor';
import ReportHistory from './detector/ReportHistory';
import { PremiumGate } from './detector/DetectorShared';
import { useAuth } from '@/contexts/AuthContext';

// ─── Lazy-loaded marketing sections ──────────────────────────────────────────
const DetectorPageSections = lazy(() => import('./detector/DetectorPageSections'));
const DetectorPageBottom = lazy(() => import('./detector/DetectorPageBottom'));

// ─── SEO Schemas ─────────────────────────────────────────────────────────────
const SCHEMAS = [
  {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: 'AI Detector – Detect AI-Generated Content with Industry-Leading Accuracy',
    description: 'Free AI detector and AI checker tool. Detect ChatGPT, GPT-5.5, Gemini, Claude, DeepSeek, and other AI-generated content instantly with sentence-level analysis.',
    url: 'https://www.aidetector.cx/detector',
    inLanguage: 'en',
    dateModified: '2025-06-01',
    breadcrumb: {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.aidetector.cx' },
        { '@type': 'ListItem', position: 2, name: 'AI Detector', item: 'https://www.aidetector.cx/detector' },
      ],
    },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'AIDetector.cx – AI Detector',
    applicationCategory: 'UtilitiesApplication',
    operatingSystem: 'Web',
    url: 'https://www.aidetector.cx/detector',
    description: 'Industry-leading AI content detector. Instantly identify AI-generated text from ChatGPT, GPT-5.5, Gemini, Claude, DeepSeek, Grok, Llama, Mistral, and more.',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD', availability: 'https://schema.org/InStock' },
    aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.9', reviewCount: '18432', bestRating: '5' },
    featureList: [
      'AI Probability Score', 'Sentence-level AI Analysis', 'File Upload Support',
      'GPT-5.5 Detection', 'ChatGPT Detection', 'Gemini Detection', 'Claude Detection',
      'Multi-language Support', 'Detailed Reports', 'API Access',
    ],
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'AIDetector.cx',
    url: 'https://www.aidetector.cx',
    logo: 'https://www.aidetector.cx/logo.png',
    description: 'AIDetector.cx provides industry-leading AI content detection, humanization, plagiarism checking, and SEO tools.',
    sameAs: ['https://twitter.com/aidetectorcx'],
  },
  {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name: 'How to Detect AI-Generated Content',
    description: 'Use the AIDetector.cx AI checker to identify AI-generated text in four steps.',
    step: [
      { '@type': 'HowToStep', position: 1, name: 'Paste or Upload', text: 'Paste your text directly into the detector or upload a DOCX, PDF, or TXT file.' },
      { '@type': 'HowToStep', position: 2, name: 'AI Analysis', text: 'Our AI content detector analyzes linguistic patterns, perplexity, and burstiness.' },
      { '@type': 'HowToStep', position: 3, name: 'Probability Score', text: 'The AI detector calculates a human vs. AI probability score for the entire document.' },
      { '@type': 'HowToStep', position: 4, name: 'Review Report', text: 'Review sentence-level highlighting and a detailed detection report.' },
    ],
  },
  {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      { '@type': 'Question', name: 'What is an AI detector?', acceptedAnswer: { '@type': 'Answer', text: 'An AI detector is a tool that analyzes text to determine whether it was written by a human or generated by an AI model like ChatGPT, GPT-5.5, Gemini, or Claude. It uses statistical analysis of language patterns, perplexity, and burstiness to produce a probability score.' } },
      { '@type': 'Question', name: 'How accurate is AIDetector.cx?', acceptedAnswer: { '@type': 'Answer', text: 'AIDetector.cx achieves up to 98.7% accuracy on GPT-5.5 content in internal benchmarks. Accuracy varies by model and writing style. No AI detector is 100% accurate, and results should be used as one signal among many.' } },
      { '@type': 'Question', name: 'Can ChatGPT be detected?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. ChatGPT-generated text has distinctive statistical patterns including low perplexity and low burstiness that our AI checker identifies with high confidence.' } },
      { '@type': 'Question', name: 'Can GPT-5.5 be detected?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. AIDetector.cx is trained on GPT-5.5 output and achieves 98.7% detection accuracy in benchmarks. GPT-5.5 produces highly polished text, but its token probability distributions remain statistically detectable.' } },
      { '@type': 'Question', name: 'Is the AI detector free?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. AIDetector.cx offers a free plan with generous monthly limits. Pro plans unlock unlimited checks, file uploads, API access, and advanced analytics.' } },
    ],
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Review',
    itemReviewed: { '@type': 'SoftwareApplication', name: 'AIDetector.cx' },
    reviewRating: { '@type': 'Rating', ratingValue: '5', bestRating: '5' },
    author: { '@type': 'Person', name: 'Dr. Sarah Mitchell' },
    reviewBody: 'AIDetector.cx catches what TurnItIn misses. The sentence-level highlighting is invaluable for our academic integrity review process.',
  },
];

// ─── Tab configuration ───────────────────────────────────────────────────────
type TabId = 'text' | 'image' | 'video' | 'deepfake-image' | 'deepfake-video' | 'voice' | 'plagiarism' | 'hallucination' | 'citation' | 'monitor' | 'history';

const TABS: { id: TabId; label: string; icon: any; badge?: string }[] = [
  { id: 'text', label: 'AI Text Detector', icon: FileText },
  { id: 'image', label: 'AI Image Detector', icon: ImageIcon },
  { id: 'video', label: 'AI Video Detector', icon: Video, badge: 'Premium' },
  { id: 'deepfake-image', label: 'Deepfake Image', icon: ScanFace, badge: 'Premium' },
  { id: 'deepfake-video', label: 'Deepfake Video', icon: ScanFace, badge: 'Premium' },
  { id: 'voice', label: 'AI Voice Detector', icon: Mic, badge: 'Premium' },
  { id: 'plagiarism', label: 'Plagiarism Detector', icon: TextSearch },
  { id: 'hallucination', label: 'Hallucination Detector', icon: ShieldAlert },
  { id: 'citation', label: 'Citation Verifier', icon: Quote },
  { id: 'monitor', label: 'Writing Monitor', icon: Activity, badge: 'Premium' },
  { id: 'history', label: 'Report History', icon: ClipboardList },
];

// ─── Trust strip items ───────────────────────────────────────────────────────
const TRUST_ITEMS = [
  { icon: FileText, label: '12.4M+ documents analyzed' },
  { icon: Zap, label: '1.2s avg processing' },
  { icon: Shield, label: 'GPT-5.5, ChatGPT, Gemini, Claude, DeepSeek, Grok, Llama, Mistral' },
  { icon: Lock, label: 'Secure & privacy-first' },
  { icon: Globe, label: '142+ countries served' },
  { icon: CheckCircle2, label: '98.7% detection accuracy' },
];

// ─── Main DetectorPage ────────────────────────────────────────────────────────
export default function DetectorPage() {
  const [activeTab, setActiveTab] = useState<TabId>('text');
  const { profile } = useAuth();

  const currentPlan = profile?.subscription_plan || 'free';
  const isAdmin = profile?.role === 'admin';
  const isPaid = currentPlan === 'pro' || currentPlan === 'business' || currentPlan === 'enterprise';
  const hasPremiumAccess = isPaid || isAdmin;

  const scrollToDetector = () => {
    document.getElementById('detector-tool')?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <MainLayout>
      <PageMeta
        title="AI Detector – Detect AI-Generated Content with Industry-Leading Accuracy | AIDetector.cx"
        description="Free AI detector and AI checker. Instantly detect ChatGPT, GPT-5.5, Gemini, Claude, DeepSeek, and other AI-generated content. Sentence-level analysis, file upload, API access. Trusted by 1M+ users."
        canonicalUrl="https://www.aidetector.cx/detector"
        ogTitle="AI Detector – Industry-Leading AI Content Detection | AIDetector.cx"
        schemas={SCHEMAS}
      />

      {/* ── Breadcrumb (visible) ─────────────────────────────────────────── */}
      <nav aria-label="Breadcrumb" className="bg-muted/40 border-b border-border/50">
        <div className="max-w-6xl mx-auto px-4 md:px-6 py-2 flex items-center gap-2 text-xs text-muted-foreground">
          <Link to="/" className="hover:text-primary transition-colors">Home</Link>
          <span>/</span>
          <span className="text-foreground font-medium">AI Detector</span>
        </div>
      </nav>

      {/* ── Hero ─────────────────────────────────────────────────────────── */}
      <section className="bg-gradient-to-b from-primary/5 via-background to-background pt-10 pb-6 px-4 md:px-6">
        <div className="max-w-6xl mx-auto">
          <div className="max-w-3xl">
            <Badge variant="secondary" className="mb-4 text-xs font-semibold">
              🏆 #1 Rated AI Detector 2025
            </Badge>
            <h1 className="text-3xl md:text-4xl font-extrabold text-navy leading-tight text-balance mb-4">
              AI Detector – Detect AI-Generated Content with Industry-Leading Accuracy
            </h1>
            <p className="text-base text-muted-foreground leading-relaxed mb-6 max-w-2xl text-pretty">
              The most trusted <strong>AI detector</strong> and <strong>AI checker</strong> on the web. Instantly scan text for ChatGPT,{' '}
              <strong>GPT-5.5 detector</strong>, Gemini, Claude, DeepSeek, Grok, Llama, and Mistral output. Our{' '}
              <strong>AI content detector</strong> gives you sentence-level highlighting, confidence scores, and detailed
              reports — making it the complete <strong>ChatGPT detector</strong> for academics, publishers, businesses, and creators.
            </p>
            <div className="flex flex-wrap gap-3 mb-8">
              <Button size="lg" className="gap-2 font-semibold" onClick={scrollToDetector}>
                <Shield className="w-4 h-4" />
                Detect AI Content
              </Button>
              <Button size="lg" variant="outline" className="gap-2 font-semibold" onClick={scrollToDetector}>
                <Upload className="w-4 h-4" />
                Upload Document
              </Button>
            </div>
            {/* Trust strip */}
            <div className="flex flex-wrap gap-x-5 gap-y-2">
              {TRUST_ITEMS.map((item) => {
                const Icon = item.icon;
                return (
                  <div key={item.label} className="flex items-center gap-1.5 text-xs text-muted-foreground">
                    <Icon className="w-3.5 h-3.5 text-primary shrink-0" />
                    <span>{item.label}</span>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </section>

      {/* ── Detector Tool (above the fold, unchanged) ────────────────────── */}
      <section id="detector-tool" className="py-6 px-4 md:px-6">
        <div className="max-w-6xl mx-auto">
          {/* Tab bar */}
          <div className="border-b border-border mb-8 overflow-x-auto">
            <nav className="flex gap-0 min-w-max" aria-label="Detector tools">
              {TABS.map(tab => {
                const Icon = tab.icon;
                const isActive = activeTab === tab.id;
                return (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id)}
                    className={`flex items-center gap-2 px-4 py-3 text-sm font-medium border-b-2 transition-colors whitespace-nowrap ${
                      isActive
                        ? 'border-primary text-primary'
                        : 'border-transparent text-muted-foreground hover:text-navy hover:border-border'
                    }`}
                  >
                    <Icon className="w-4 h-4" />
                    {tab.label}
                    {tab.badge && (
                      <span className="text-[10px] font-semibold bg-primary/10 text-primary px-1.5 py-0.5 rounded-full leading-none">
                        {tab.badge}
                      </span>
                    )}
                  </button>
                );
              })}
            </nav>
          </div>

          {/* Tab content — all original logic preserved */}
          <div>
            {(() => {
              const currentTabConfig = TABS.find(t => t.id === activeTab);
              if (currentTabConfig?.badge === 'Premium' && !hasPremiumAccess) {
                return <PremiumGate feature={currentTabConfig.label} />;
              }
              switch (activeTab) {
                case 'text': return <AITextDetector />;
                case 'image': return <AIImageDetector />;
                case 'video': return <AIVideoDetector />;
                case 'deepfake-image': return <DeepfakeImageDetector />;
                case 'deepfake-video': return <DeepfakeVideoDetector />;
                case 'voice': return <AIVoiceDetector />;
                case 'plagiarism': return <PlagiarismDetector />;
                case 'hallucination': return <HallucinationDetector />;
                case 'citation': return <CitationVerifier />;
                case 'monitor': return <WritingMonitor />;
                case 'history': return <ReportHistory />;
                default: return <AITextDetector />;
              }
            })()}
          </div>
        </div>
      </section>

      {/* ── Marketing sections (lazy-loaded for Core Web Vitals) ─────────── */}
      <Suspense fallback={null}>
        <DetectorPageSections />
      </Suspense>
      <Suspense fallback={null}>
        <DetectorPageBottom />
      </Suspense>

      {/* ── Sticky mobile CTA ─────────────────────────────────────────────── */}
      <div className="fixed bottom-0 left-0 right-0 z-40 md:hidden bg-background/95 backdrop-blur border-t border-border px-4 py-3">
        <Button className="w-full gap-2 font-semibold" onClick={scrollToDetector}>
          <Shield className="w-4 h-4" />
          Detect AI Content Free
        </Button>
      </div>
    </MainLayout>
  );
}
