import { useState } from 'react';
import { ChevronDown } from 'lucide-react';
import { Link } from 'react-router-dom';
import { cn } from '@/lib/utils';

export const FAQ_DATA = [
  {
    question: 'What is an AI detector?',
    answer:
      'An AI detector (also called an AI content detector or AI checker) is a tool that analyzes a piece of text and estimates the probability that it was generated by a language model such as ChatGPT, Claude, or Gemini. It does this by examining statistical, linguistic, and structural patterns in the writing that tend to differ between machine-generated and human-written text.',
  },
  {
    question: 'How does an AI detector work?',
    answer:
      'AI detectors examine signals in the text — things like sentence structure variation, vocabulary distribution, predictability of word choices, and stylistic consistency — that differ between human and AI writing. The detector does not match text against a database of known AI outputs; it analyses the writing itself. AIDetector.cx runs two independent engines (Balanced and High-Sensitivity) and also provides a sentence-level breakdown so you can see which specific passages carry the strongest signals.',
  },
  {
    question: 'Can AI detectors detect ChatGPT?',
    answer:
      'Yes, to a degree. AIDetector.cx is designed to detect writing patterns associated with large language models including ChatGPT, Claude, and Gemini. Because these models share similar training and generation approaches, patterns learned across models are often transferable. However, results are probabilistic — the detector estimates likelihood, not certainty — and heavily edited or paraphrased AI text may score lower than raw output.',
  },
  {
    question: 'How accurate are AI detectors?',
    answer:
      'There is no universal accuracy figure because performance varies significantly depending on text length, writing style, language, model used to generate the text, and how much the text has been edited. Short texts (under 100 words) are less reliable than longer samples. We do not publish an accuracy percentage we cannot substantiate. The honest answer is that no AI detector is perfectly accurate and results should be treated as one signal among several.',
  },
  {
    question: 'Can AI detectors be wrong?',
    answer:
      'Yes. Both false positives (human text flagged as AI) and false negatives (AI text not flagged) occur. Formal academic writing, technical prose, and highly structured human text are more prone to false positives. AI text that has been substantially rewritten or paraphrased is more likely to produce false negatives. This is why results should never be used as the sole basis for consequential decisions.',
  },
  {
    question: 'Can AI detectors detect human-edited AI?',
    answer:
      'It depends on the degree of editing. Minor rewrites often preserve enough of the original AI patterns to be flagged. Substantial paraphrasing, rewriting, or blending with original human writing disrupts those patterns and can produce lower AI probability scores. The High-Sensitivity mode is more likely to flag borderline cases, though with a higher risk of false positives.',
  },
  {
    question: 'Does AIDetector.cx support multiple languages?',
    answer:
      'Yes. The detector supports 19+ languages including English, Spanish, Arabic, French, German, Portuguese, Italian, Dutch, Russian, Chinese, Japanese, Korean, and others. Each language has an explicit support status (Validated, Beta, or Experimental). Detection uses language-aware calibration rather than applying English-language assumptions across all text.',
  },
  {
    question: 'Can teachers detect AI-written essays?',
    answer:
      'An AI detector for teachers can be a useful starting point for reviewing writing patterns in submitted essays, but it should never be used as the sole evidence of academic misconduct. Detector results indicate probability, not authorship proof. Educators should use results alongside assignment context, student writing history, classroom observation, and institutional academic integrity policies before drawing any conclusions.',
  },
  {
    question: 'What does "Mixed" mean in the results?',
    answer:
      'A Mixed result means the detector identified portions of the text with AI-like patterns alongside portions that read as human-written — rather than the entire document trending clearly in one direction. This can occur in documents co-authored by a human and an AI model, or in human-written text where some sections happen to closely resemble AI output patterns.',
  },
  {
    question: 'Why can the two detection modes disagree?',
    answer:
      'The Balanced and High-Sensitivity engines use different calibration thresholds. The Balanced mode is tuned to reduce false positives; the High-Sensitivity mode applies stricter thresholds and detects weaker AI-like signals at the cost of more false positives. For borderline text, disagreement between the two is expected and informative — it signals genuine ambiguity rather than an error. When both modes agree strongly, the combined evidence is more meaningful.',
  },
  {
    question: 'How much text should I test?',
    answer:
      'For the most reliable results, use complete documents or passages of at least 200–300 words. Very short texts (under 100 words) provide limited signal and results should be treated cautiously. For longer documents, reviewing the sentence-level breakdown on the full detector page helps identify which specific sections drive the overall score.',
  },
  {
    question: 'Is AIDetector.cx free?',
    answer:
      'Yes. A free plan is available with no credit card required and no time limit. Premium plans unlock higher usage limits, bulk analysis, and access to additional tools. You can start using the AI detector immediately without creating an account.',
  },
];

function FAQItem({ question, answer, isOpen, onToggle }: {
  question: string;
  answer: string;
  isOpen: boolean;
  onToggle: () => void;
}) {
  return (
    <div className="border-b border-border/50 last:border-b-0">
      <button
        onClick={onToggle}
        className="w-full flex items-start justify-between gap-4 py-5 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/60 rounded-sm"
        aria-expanded={isOpen}
      >
        <span className="font-semibold text-foreground text-sm md:text-base leading-snug">{question}</span>
        <ChevronDown
          className={cn(
            'w-5 h-5 text-muted-foreground shrink-0 mt-0.5 transition-transform duration-200',
            isOpen && 'rotate-180'
          )}
        />
      </button>
      {isOpen && (
        <p className="pb-5 text-sm md:text-base text-muted-foreground leading-relaxed text-pretty pr-9">
          {answer}
        </p>
      )}
    </div>
  );
}

export default function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const toggle = (i: number) => setOpenIndex(openIndex === i ? null : i);

  return (
    <section className="py-16 md:py-24 bg-muted/20" aria-labelledby="faq-heading">
      <div className="max-w-4xl mx-auto px-4 sm:px-6">
        <div className="text-center max-w-2xl mx-auto mb-12">
          <h2
            id="faq-heading"
            className="text-2xl md:text-4xl font-extrabold tracking-tight text-foreground mb-4 text-balance"
          >
            Frequently Asked Questions
          </h2>
          <p className="text-base md:text-lg text-muted-foreground text-pretty">
            Honest answers about how AI detection works, what the results mean, and where the limits are.
          </p>
        </div>

        <div className="bg-card rounded-2xl border border-border/50 px-6 divide-y-0">
          {FAQ_DATA.map((item, i) => (
            <FAQItem
              key={item.question}
              question={item.question}
              answer={item.answer}
              isOpen={openIndex === i}
              onToggle={() => toggle(i)}
            />
          ))}
        </div>

        <p className="mt-6 text-center text-sm text-muted-foreground">
          More questions?{' '}
          <Link to="/guides" className="text-primary underline underline-offset-4 hover:no-underline">
            Browse our AI detection guides
          </Link>{' '}
          or{' '}
          <Link to="/contact" className="text-primary underline underline-offset-4 hover:no-underline">
            contact us
          </Link>
          .
        </p>
      </div>
    </section>
  );
}
