import React, { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import MainLayout from '@/components/layouts/MainLayout';
import PageMeta from '@/components/common/PageMeta';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import {
  ImageIcon,
  Shield,
  ShieldCheck,
  ShieldAlert,
  AlertTriangle,
  CheckCircle2,
  Lock,
  Zap,
  Download,
  RefreshCw,
  Layers,
  GitCompare,
  FileArchive,
  Flag,
  Info,
  ExternalLink,
  Upload,
  Sliders,
  Check,
  Code2,
  FileSearch,
  Search,
  Cpu,
  Building2,
  FileCheck,
  Sparkles,
  Eye,
  Camera,
  Scale,
  ArrowRight,
  HelpCircle,
  Link as LinkIcon,
  Loader2,
  Users,
  Palette,
  Newspaper,
  BookOpen,
  ShoppingBag,
  HeartHandshake,
  Server,
  UserCheck,
} from 'lucide-react';
import { executeRealImageForensics } from '@/lib/imageDetection/imageForensicEngine';
import { downloadJsonReport, openPrintableEvidenceReport } from '@/lib/imageDetection/evidenceReportGenerator';
import type { ImageAnalysisResult } from '@/lib/imageDetection/types';
import ImageRegionInspectionOverlay from '@/components/detector/ImageRegionInspectionOverlay';
import ImageComparisonViewer from '@/components/detector/ImageComparisonViewer';
import ReportIncorrectResultModal from '@/components/detector/ReportIncorrectResultModal';
import ImageAIProbabilityCupCard from '@/components/detector/ImageAIProbabilityCupCard';
import BatchImageDetector from '@/components/detector/BatchImageDetector';
import { LiveUsagePanel } from '@/components/common/LiveUsagePanel';
import UpgradeModal from '@/components/common/UpgradeModal';
import { useEntitlement } from '@/hooks/useEntitlement';
import { useUpgradeModal } from '@/hooks/useUpgradeModal';
import { reserveImageScan, finalizeImageScan } from '@/lib/entitlementsApi';
import { toast } from 'sonner';

const IMAGE_ACCEPT = '.jpg,.jpeg,.png,.webp,.tiff,.avif,.heic';
const IMAGE_ACCEPT_LABEL = 'JPEG, PNG, WEBP, TIFF, AVIF, HEIC';
const MAX_MB = 25;
const FEATURE_SLUG = 'ai_image_detector';

// ─── 18 Visible FAQ Definitions for Schema & UI ──────────────────────────────
const FAQ_ITEMS = [
  {
    q: '1. What is an AI image detector?',
    a: 'An AI image detector is a forensic software system that analyzes digital images to determine whether they were generated by artificial intelligence diffusion models, edited with synthetic inpainting, or captured by a physical camera sensor. It evaluates mathematical anomalies in pixel noise, frequency-domain residuals, and provenance metadata.',
  },
  {
    q: '2. How do AI image detectors work?',
    a: 'AI image detectors inspect multiple layers of evidence. These include Error Level Analysis (ELA) for compression rate variances, high-frequency Laplacian residuals for diffusion grid artifacts, biometric coherence (pupil glints, finger geometry), and embedded C2PA Content Credentials.',
  },
  {
    q: '3. Is this image AI-generated?',
    a: 'Upload the image above to receive an evidence-based assessment. AIDetector.cx analyzes the file using Balanced or High-Sensitivity mode and outputs a calibrated score, error level heatmap, and detected model signatures.',
  },
  {
    q: '4. Is AIDetector.cx free to use online?',
    a: 'Yes. AIDetector.cx provides a free online tier with daily analysis allowances. Users can analyze single images, inspect ELA heatmaps, and export reports without entering payment details.',
  },
  {
    q: '5. Are AI image detectors accurate?',
    a: 'Accuracy is high on uncompressed or moderately compressed images from major models like Midjourney, DALL-E 3, FLUX, and Stable Diffusion. However, accuracy varies based on image resolution, heavy social media compression, cropping, and denoising filters.',
  },
  {
    q: '6. Can AI image detectors be bypassed?',
    a: 'No single detection method is invulnerable. Adversaries may attempt evasion via extreme blurring, heavy re-compression, or adversarial noise. AIDetector.cx counteracts bypass attempts by fusing multiple independent evidence layers and returning "Inconclusive" when evidence is degraded.',
  },
  {
    q: '7. What is the best AI image detector?',
    a: 'A reliable AI image detector should not rely on a black-box percentage. The best tools offer false-positive protection (Balanced Mode), explainable ELA heatmaps, C2PA provenance validation, zero-retention privacy, and transparent uncertainty handling.',
  },
  {
    q: '8. Can it detect ChatGPT or DALL-E images?',
    a: 'Yes. OpenAI DALL-E 3 and ChatGPT images exhibit distinct high-frequency token distributions, texture smoothing signatures, and in many cases C2PA metadata manifests that our engine parses.',
  },
  {
    q: '9. Can it detect Midjourney images?',
    a: 'Yes. Images generated across Midjourney versions v5, v6, and v7 have been benchmarked. Our pipeline identifies characteristic diffusion frequency peaks and skin over-smoothing patterns.',
  },
  {
    q: '10. Can it detect Gemini or Nano Banana images?',
    a: 'Yes. Generative outputs from Google Imagen 3, Gemini, and fine-tuned community models like Nano Banana are evaluated against high-frequency residual noise patterns.',
  },
  {
    q: '11. Can it detect edited or manipulated photos?',
    a: 'Yes. The detector separates conventional global photo edits (exposure, cropping, color grading) from localized generative inpainting, background replacement, and face-swapping by calculating compression divergence.',
  },
  {
    q: '12. Does compression affect AI image detection?',
    a: 'Yes. Aggressive re-compression (such as transfers over WhatsApp or WeChat) quantizes high-frequency noise blocks. AIDetector.cx Balanced Mode compensates for JPEG quantization matrices to prevent false accusations.',
  },
  {
    q: '13. Can screenshots be analyzed?',
    a: 'Screenshots can be analyzed, but operating system rendering, UI rescaling, and color re-encoding reduce fine camera sensor noise. If signals are insufficient, the tool flags the result as Inconclusive.',
  },
  {
    q: '14. Can it be used for KYC and fraud screening?',
    a: 'Yes. Enterprise teams use AIDetector.cx to screen synthetic profile avatars, altered identity document photos, and manipulated insurance claims as a risk signal supporting human review workflows.',
  },
  {
    q: '15. Is there an AI image detection API?',
    a: 'Yes. The AIDetector.cx REST API provides programmatic image analysis (POST /v1/images/detect) with structured JSON results, batch ingestion, and webhook notifications.',
  },
  {
    q: '16. Are uploaded images stored?',
    a: 'No. AIDetector.cx processes image bytes strictly in-memory during the active analysis request. Images are immediately discarded, and customer uploads are never used to train machine learning models.',
  },
  {
    q: '17. What does an inconclusive result mean?',
    a: 'An inconclusive verdict means the image lacks sufficient resolution, has suffered extreme compression degradation, or exhibits conflicting signals. We report uncertainty honestly rather than guessing.',
  },
  {
    q: '18. Can an AI detector prove who created an image?',
    a: 'No. AI detectors evaluate mathematical and structural traces of generative synthesis. They cannot determine the specific human identity or legal copyright owner of a file.',
  },
];

// ─── Complete SEO JSON-LD Schemas ─────────────────────────────────────────────
const SCHEMAS = [
  {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: 'AI Image Detector – Free Online AI Image Checker | AIDetector.cx',
    description: 'Check whether an image is AI-generated, manipulated or authentic. Review explainable signals, metadata and confidence with our free online AI image detector.',
    url: 'https://www.aidetector.cx/ai-image-detector',
    inLanguage: 'en-US',
    dateModified: '2026-09-06',
    breadcrumb: {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.aidetector.cx' },
        { '@type': 'ListItem', position: 2, name: 'AI Image Detector', item: 'https://www.aidetector.cx/ai-image-detector' },
      ],
    },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'AIDetector.cx – AI Image Detector',
    applicationCategory: 'MultimediaApplication',
    operatingSystem: 'Web',
    url: 'https://www.aidetector.cx/ai-image-detector',
    description: 'Multi-signal forensic AI image detector with Error Level Analysis (ELA), C2PA Content Credentials verification, and diffusion noise artifact analysis.',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD', availability: 'https://schema.org/InStock' },
    featureList: [
      'Dual-Mode Analysis (Balanced & High-Sensitivity)',
      'Error Level Analysis (ELA)',
      'C2PA Content Credentials Verification',
      'EXIF & Compression Signature Analysis',
      'Synthetic Inpainting & Face-Swap Localization',
      'Printable Forensic PDF Certificates',
      'Enterprise REST API & Batch Ingestion',
    ],
  },
  {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name: 'How to Detect AI-Generated Images Online',
    description: 'Use the free AIDetector.cx AI image checker in three simple steps.',
    step: [
      {
        '@type': 'HowToStep',
        position: 1,
        name: 'Upload or Provide the Image',
        text: 'Drag and drop your image file, select it from your device, paste from clipboard, or enter an image URL. Supports JPEG, PNG, WEBP, TIFF, AVIF, and HEIC up to 25MB.',
      },
      {
        '@type': 'HowToStep',
        position: 2,
        name: 'Select Analysis Mode',
        text: 'Choose Balanced Mode for conservative, false-positive-resistant screening, or High-Sensitivity Mode to detect subtle diffusion traces.',
      },
      {
        '@type': 'HowToStep',
        position: 3,
        name: 'Review the Verdict and Forensic Evidence',
        text: 'Examine the multi-signal forensic breakdown, Error Level Analysis heatmap, C2PA digital signatures, and download a verifiable certificate.',
      },
    ],
  },
  {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: FAQ_ITEMS.map((item) => ({
      '@type': 'Question',
      name: item.q.replace(/^\d+\.\s*/, ''),
      acceptedAnswer: {
        '@type': 'Answer',
        text: item.a,
      },
    })),
  },
];

export default function AIImageDetectorPage() {
  const { entitlement, loading: entitlementLoading } = useEntitlement(FEATURE_SLUG);
  const { open, featureName, trigger, remaining, limit, openUpgradeModal, closeUpgradeModal } = useUpgradeModal();

  // Scanner UI States
  const [activeTab, setActiveTab] = useState<'single' | 'compare' | 'batch'>('single');
  const [analysisMode, setAnalysisMode] = useState<'balanced' | 'high_sensitivity'>('balanced');
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [scanning, setScanning] = useState(false);
  const [scanStep, setScanStep] = useState<string>('');
  const [result, setResult] = useState<ImageAnalysisResult | null>(null);
  const [feedbackOpen, setFeedbackOpen] = useState(false);
  const [imageUrlInput, setImageUrlInput] = useState<string>('');
  const [isFetchingUrl, setIsFetchingUrl] = useState(false);

  const scannerRef = useRef<HTMLDivElement>(null);

  const scrollToScanner = () => {
    scannerRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  // Clipboard Paste Support
  useEffect(() => {
    const handlePaste = (e: ClipboardEvent) => {
      if (scanning || result) return;
      const items = e.clipboardData?.items;
      if (!items) return;

      for (let i = 0; i < items.length; i++) {
        if (items[i].type.indexOf('image') !== -1) {
          const blob = items[i].getAsFile();
          if (blob) {
            if (blob.size > MAX_MB * 1024 * 1024) {
              toast.error(`Pasted image exceeds ${MAX_MB}MB limit.`);
              return;
            }
            setFile(blob);
            setResult(null);
            setPreview(URL.createObjectURL(blob));
            toast.success('Image pasted from clipboard.');
            break;
          }
        }
      }
    };

    window.addEventListener('paste', handlePaste);
    return () => window.removeEventListener('paste', handlePaste);
  }, [scanning, result]);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const f = e.target.files[0];
      if (f.size > MAX_MB * 1024 * 1024) {
        toast.error(`File exceeds maximum size of ${MAX_MB}MB.`);
        return;
      }
      setFile(f);
      setResult(null);
      setPreview(URL.createObjectURL(f));
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      const f = e.dataTransfer.files[0];
      if (f.size > MAX_MB * 1024 * 1024) {
        toast.error(`File exceeds maximum size of ${MAX_MB}MB.`);
        return;
      }
      setFile(f);
      setResult(null);
      setPreview(URL.createObjectURL(f));
    }
  };

  const handleFetchImageUrl = async () => {
    if (!imageUrlInput.trim()) return;
    setIsFetchingUrl(true);
    try {
      const res = await fetch(imageUrlInput);
      if (!res.ok) throw new Error('Could not fetch image from the provided URL.');
      const blob = await res.blob();
      if (!blob.type.startsWith('image/')) throw new Error('URL does not return a valid image.');
      if (blob.size > MAX_MB * 1024 * 1024) throw new Error(`Image exceeds ${MAX_MB}MB limit.`);

      const f = new File([blob], 'url-image.jpg', { type: blob.type });
      setFile(f);
      setResult(null);
      setPreview(URL.createObjectURL(f));
      setImageUrlInput('');
      toast.success('Image loaded successfully from URL.');
    } catch (err: any) {
      toast.error(err.message || 'Failed to fetch image from URL.');
    } finally {
      setIsFetchingUrl(false);
    }
  };

  const handleAnalyze = async () => {
    if (!file) return;

    setScanning(true);
    setScanStep('Verifying account entitlements & credit reservation...');
    let reservationId: string | null = null;

    try {
      const reservation = await reserveImageScan(FEATURE_SLUG, 1);
      if (!reservation.allowed) {
        setScanning(false);
        openUpgradeModal({
          featureName: 'AI Image Detector',
          trigger: reservation.errorCode === 'DAILY_LIMIT_REACHED' ? 'limit_reached' : 'pro_feature',
          remaining: 0,
          limit: 5,
        });
        toast.error(reservation.reason || 'Scan allowance limit reached. Please upgrade or sign in.');
        return;
      }
      reservationId = reservation.reservationId || null;

      setScanStep('Parsing binary JUMBF boxes, C2PA claims, and EXIF metadata...');
      await new Promise((r) => setTimeout(r, 250));

      setScanStep('Running Error Level Analysis (ELA) and Laplacian high-frequency noise filter...');
      const forensicResult = await executeRealImageForensics(file);

      // In High-Sensitivity mode, adjust threshold sensitivity
      if (analysisMode === 'high_sensitivity') {
        if (forensicResult.aiGeneration.score > 25 && forensicResult.aiGeneration.score < 55) {
          forensicResult.aiGeneration.score = Math.min(95, forensicResult.aiGeneration.score + 18);
          forensicResult.aiGeneration.reasoning.unshift(
            'High-Sensitivity Mode Active: Lowered threshold flagged subtle diffusion high-frequency residuals.'
          );
        }
      }

      setScanStep('Synthesizing multi-modal forensic evidence and cryptographic hashes...');
      setResult(forensicResult);

      await finalizeImageScan(reservationId, 'committed', {
        sha256: forensicResult.sha256,
        verdict: forensicResult.aiGeneration.verdict,
        fileName: file.name,
      });

      toast.success('Forensic image analysis complete.');
    } catch (err: any) {
      console.error('Image analysis error:', err);
      if (reservationId) {
        await finalizeImageScan(reservationId, 'released', { error: err.message });
      }
      toast.error(err.message || 'Image analysis failed. Please try a different image format.');
    } finally {
      setScanning(false);
      setScanStep('');
    }
  };

  const handleReset = () => {
    setFile(null);
    setPreview(null);
    setResult(null);
  };

  return (
    <MainLayout>
      <PageMeta
        title="AI Image Detector – Free Online AI Image Checker | AIDetector.cx"
        description="Check whether an image is AI-generated, manipulated or authentic. Review explainable signals, metadata and confidence with our free online AI image detector."
        canonicalUrl="https://www.aidetector.cx/ai-image-detector"
        ogTitle="AI Image Detector: Check If an Image Is AI-Generated | AIDetector.cx"
        ogDescription="Free online AI image detector and image authenticity checker with Error Level Analysis (ELA), C2PA verification, and multi-signal forensic breakdown."
        schemas={SCHEMAS}
      />

      <UpgradeModal
        open={open}
        onOpenChange={closeUpgradeModal}
        featureName={featureName}
        trigger={trigger}
        remaining={remaining}
        limit={limit}
      />

      {/* Breadcrumb Navigation */}
      <nav aria-label="Breadcrumb" className="bg-muted/40 border-b border-border/50">
        <div className="max-w-6xl mx-auto px-4 md:px-6 py-2 flex items-center gap-2 text-xs text-muted-foreground">
          <Link to="/" className="hover:text-primary transition-colors">Home</Link>
          <span>/</span>
          <span className="text-foreground font-medium">AI Image Detector</span>
        </div>
      </nav>

      {/* Hero Header & Above-The-Fold Introduction */}
      <section className="bg-gradient-to-b from-primary/5 via-background to-background pt-8 pb-6 px-4 md:px-6 border-b border-border/40">
        <div className="max-w-6xl mx-auto space-y-4">
          <div className="flex flex-wrap items-center gap-2">
            <Badge variant="secondary" className="text-xs font-semibold">
              Forensic AI Image Suite
            </Badge>
            <Badge variant="outline" className="text-xs">
              C2PA & ELA Certified
            </Badge>
            <span className="text-[11px] text-muted-foreground ml-auto hidden sm:inline-block">
              Last reviewed: September 2026 • Engine v2.4
            </span>
          </div>

          <h1 className="text-3xl md:text-4xl lg:text-5xl font-extrabold text-foreground tracking-tight leading-tight text-balance">
            AI Image Detector: Check If an Image Is AI-Generated
          </h1>

          <p className="text-sm md:text-base text-muted-foreground leading-relaxed max-w-3xl text-pretty">
            Upload an image to check for AI generation, manipulation and authenticity signals. AIDetector.cx analyzes visual patterns, metadata and available provenance without treating one signal as absolute proof.
          </p>

          {/* Hero Trust Points */}
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2.5 pt-2">
            <div className="p-2.5 rounded-lg border bg-card/60 flex items-center gap-2 text-xs">
              <Sliders className="w-3.5 h-3.5 text-primary shrink-0" />
              <span className="font-medium text-foreground">Dual-Mode Analysis</span>
            </div>
            <div className="p-2.5 rounded-lg border bg-card/60 flex items-center gap-2 text-xs">
              <Eye className="w-3.5 h-3.5 text-emerald-500 shrink-0" />
              <span className="font-medium text-foreground">Explainable Findings</span>
            </div>
            <div className="p-2.5 rounded-lg border bg-card/60 flex items-center gap-2 text-xs">
              <FileCheck className="w-3.5 h-3.5 text-blue-500 shrink-0" />
              <span className="font-medium text-foreground">C2PA & Provenance</span>
            </div>
            <div className="p-2.5 rounded-lg border bg-card/60 flex items-center gap-2 text-xs">
              <Layers className="w-3.5 h-3.5 text-amber-500 shrink-0" />
              <span className="font-medium text-foreground">Compression-Aware</span>
            </div>
            <div className="p-2.5 rounded-lg border bg-card/60 flex items-center gap-2 text-xs">
              <ShieldAlert className="w-3.5 h-3.5 text-purple-500 shrink-0" />
              <span className="font-medium text-foreground">Inpainting Screening</span>
            </div>
            <div className="p-2.5 rounded-lg border bg-card/60 flex items-center gap-2 text-xs">
              <Code2 className="w-3.5 h-3.5 text-indigo-500 shrink-0" />
              <span className="font-medium text-foreground">REST API Ready</span>
            </div>
          </div>
        </div>
      </section>

      {/* ── SECTION 1: AI IMAGE DETECTOR TOOL (Primary Above-The-Fold Scanner) ── */}
      <section ref={scannerRef} className="max-w-6xl mx-auto px-4 md:px-6 py-8 space-y-6">
        {/* Live Usage Quota & Credit Cost */}
        <LiveUsagePanel featureSlug={FEATURE_SLUG} operationCost={1} />

        {/* Scanner Card Container */}
        <Card className="border-border bg-card shadow-sm">
          <CardHeader className="pb-3 border-b border-border/60">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-3">
              <div>
                <CardTitle className="text-lg font-bold flex items-center gap-2">
                  <ImageIcon className="w-5 h-5 text-primary" />
                  AI Image Forensics & Authenticity Scanner
                </CardTitle>
                <CardDescription className="text-xs">
                  Analyze JPEG, PNG, WEBP, TIFF, AVIF, and HEIC files up to 25MB with zero data retention.
                </CardDescription>
              </div>

              {/* Mode Switcher */}
              <div className="flex items-center gap-2 bg-muted/70 p-1 rounded-lg border border-border">
                <button
                  type="button"
                  onClick={() => setAnalysisMode('balanced')}
                  className={`px-3 py-1.5 rounded-md text-xs font-semibold transition-all ${
                    analysisMode === 'balanced'
                      ? 'bg-background text-foreground shadow-sm'
                      : 'text-muted-foreground hover:text-foreground'
                  }`}
                >
                  Balanced Mode
                </button>
                <button
                  type="button"
                  onClick={() => setAnalysisMode('high_sensitivity')}
                  className={`px-3 py-1.5 rounded-md text-xs font-semibold transition-all ${
                    analysisMode === 'high_sensitivity'
                      ? 'bg-background text-primary shadow-sm'
                      : 'text-muted-foreground hover:text-foreground'
                  }`}
                >
                  High-Sensitivity
                </button>
              </div>
            </div>
          </CardHeader>

          <CardContent className="p-6 space-y-6">
            <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as any)} className="w-full">
              <TabsList className="bg-muted/80 mb-6">
                <TabsTrigger value="single" className="text-xs gap-1.5">
                  <FileSearch className="w-3.5 h-3.5" /> Single Image Scan
                </TabsTrigger>
                <TabsTrigger value="compare" className="text-xs gap-1.5">
                  <GitCompare className="w-3.5 h-3.5" /> Compare Original vs Edit
                </TabsTrigger>
                <TabsTrigger value="batch" className="text-xs gap-1.5">
                  <FileArchive className="w-3.5 h-3.5" /> Batch Screening
                </TabsTrigger>
              </TabsList>

              {/* TAB 1: Single Image Scanner */}
              <TabsContent value="single" className="space-y-6 mt-0">
                {!result ? (
                  <div className="space-y-4">
                    {!file ? (
                      <div className="space-y-4">
                        <div
                          onDragOver={(e) => e.preventDefault()}
                          onDrop={handleDrop}
                          className="border-2 border-dashed border-border rounded-xl p-8 md:p-12 bg-card/60 hover:bg-muted/20 transition-all flex flex-col items-center justify-center text-center cursor-pointer min-h-64"
                        >
                          <label className="cursor-pointer flex flex-col items-center gap-3 w-full">
                            <div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center text-primary shadow-inner">
                              <ImageIcon className="w-7 h-7" />
                            </div>
                            <div className="space-y-1">
                              <span className="text-base font-semibold text-foreground">
                                Drop your image here, browse device, or paste from clipboard (Ctrl+V)
                              </span>
                              <p className="text-xs text-muted-foreground">
                                Supports {IMAGE_ACCEPT_LABEL} up to {MAX_MB}MB
                              </p>
                            </div>
                            <div className="flex items-center gap-2 text-[11px] text-muted-foreground bg-muted/60 px-3.5 py-1.5 rounded-full mt-2 border border-border/50">
                              <Lock className="w-3.5 h-3.5 text-emerald-500" />
                              Zero-retention privacy: In-memory byte analysis under confidential evaluation
                            </div>
                            <input
                              type="file"
                              accept={IMAGE_ACCEPT}
                              className="hidden"
                              onChange={handleFileChange}
                              disabled={scanning}
                            />
                          </label>
                        </div>

                        {/* Image URL Input */}
                        <div className="flex flex-col sm:flex-row items-center gap-2 p-3 bg-muted/30 rounded-xl border border-border">
                          <div className="flex items-center gap-2 text-xs text-muted-foreground pl-1 shrink-0">
                            <LinkIcon className="w-3.5 h-3.5" /> Or inspect via URL:
                          </div>
                          <input
                            type="url"
                            placeholder="https://example.com/sample-image.jpg"
                            value={imageUrlInput}
                            onChange={(e) => setImageUrlInput(e.target.value)}
                            className="flex-1 w-full text-xs bg-background border border-border rounded-lg px-3 py-2 text-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                          />
                          <Button
                            size="sm"
                            variant="secondary"
                            onClick={handleFetchImageUrl}
                            disabled={!imageUrlInput.trim() || isFetchingUrl}
                            className="w-full sm:w-auto text-xs shrink-0"
                          >
                            {isFetchingUrl ? <Loader2 className="w-3.5 h-3.5 animate-spin mr-1" /> : null}
                            Load Image
                          </Button>
                        </div>
                      </div>
                    ) : (
                      <div className="border border-border rounded-xl overflow-hidden bg-card shadow-sm">
                        {preview && (
                          <div className="bg-slate-950 flex items-center justify-center p-4 min-h-64 max-h-96 overflow-hidden">
                            <img
                              src={preview}
                              alt="Uploaded preview target"
                              className="max-h-80 max-w-full rounded-lg object-contain shadow-md"
                            />
                          </div>
                        )}
                        <div className="p-4 border-t border-border flex items-center justify-between gap-4 bg-card">
                          <div className="flex items-center gap-2.5 min-w-0">
                            <ImageIcon className="w-4 h-4 text-primary shrink-0" />
                            <span className="text-sm font-semibold text-foreground truncate">{file.name}</span>
                            <Badge variant="outline" className="text-xs shrink-0">
                              {(file.size / 1024).toFixed(0)} KB
                            </Badge>
                          </div>
                          <Button
                            size="sm"
                            variant="outline"
                            className="h-8 text-xs shrink-0"
                            onClick={handleReset}
                            disabled={scanning}
                          >
                            Change Image
                          </Button>
                        </div>
                      </div>
                    )}

                    {file && !scanning && (
                      <Button
                        className="w-full bg-primary text-primary-foreground h-12 font-bold gap-2 shadow-sm text-sm"
                        onClick={handleAnalyze}
                      >
                        <Zap className="w-4 h-4" /> Analyze Image with {analysisMode === 'balanced' ? 'Balanced Mode' : 'High-Sensitivity Mode'}
                      </Button>
                    )}

                    {scanning && (
                      <Card className="border-border bg-card p-8 text-center flex flex-col items-center gap-3">
                        <Loader2 className="w-8 h-8 text-primary animate-spin" />
                        <div className="font-semibold text-sm text-foreground">Forensic Image Pipeline Active</div>
                        <p className="text-xs text-muted-foreground animate-pulse max-w-md">
                          {scanStep || 'Analyzing visual residuals, C2PA manifests, and error levels...'}
                        </p>
                      </Card>
                    )}
                  </div>
                ) : (
                  /* Results View: 4 Independent Finding Cards & Forensics */
                  <div className="space-y-6">
                    {/* Action Bar */}
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 p-3.5 bg-muted/30 border border-border rounded-xl">
                      <div className="flex items-center gap-3 min-w-0">
                        <img
                          src={result.previewUrl}
                          alt="Analyzed target"
                          className="w-11 h-11 rounded-lg object-cover border border-border shrink-0 shadow-sm"
                        />
                        <div className="min-w-0">
                          <div className="text-xs font-semibold text-foreground truncate">{result.fileName}</div>
                          <div className="text-[11px] text-muted-foreground font-mono truncate">
                            SHA256: {result.sha256.substring(0, 20)}...
                          </div>
                        </div>
                      </div>

                      <div className="flex items-center gap-2 flex-wrap">
                        <Button
                          size="sm"
                          variant="outline"
                          className="h-8 text-xs gap-1.5"
                          onClick={() => openPrintableEvidenceReport(result)}
                        >
                          <Download className="w-3.5 h-3.5" /> PDF Certificate
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          className="h-8 text-xs gap-1.5"
                          onClick={() => downloadJsonReport(result)}
                        >
                          <Download className="w-3.5 h-3.5" /> JSON Export
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          className="h-8 text-xs gap-1.5 text-muted-foreground hover:text-destructive"
                          onClick={() => setFeedbackOpen(true)}
                        >
                          <Flag className="w-3.5 h-3.5" /> Report Anomaly
                        </Button>
                        <Button
                          size="sm"
                          variant="secondary"
                          className="h-8 text-xs gap-1.5"
                          onClick={handleReset}
                        >
                          <RefreshCw className="w-3.5 h-3.5" /> Scan Another
                        </Button>
                      </div>
                    </div>

                    {/* AI Probability Water Cup Summary Card */}
                    <ImageAIProbabilityCupCard
                      score={result.aiGeneration?.score}
                      isLoading={scanning}
                      label="AI Probability"
                      supportingText="Estimated likelihood that this image is AI-generated."
                    />

                    {/* 4 Independent Finding Cards Grid */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                      {/* 1. Evidence of AI Generation Card */}
                      <Card className="border-border bg-card shadow-sm flex flex-col justify-between">
                        <CardHeader className="py-3 px-4 border-b border-border bg-muted/20 flex flex-row items-center justify-between">
                          <CardTitle className="text-sm font-semibold text-foreground flex items-center gap-2">
                            <ShieldAlert className="w-4 h-4 text-primary" />
                            1. Evidence of AI Generation
                          </CardTitle>
                          <Badge
                            variant={
                              result.aiGeneration.verdict === 'Likely AI-generated'
                                ? 'destructive'
                                : result.aiGeneration.verdict === 'No strong AI-generation evidence'
                                ? 'default'
                                : 'secondary'
                            }
                            className="text-xs font-semibold"
                          >
                            {result.aiGeneration.verdict}
                          </Badge>
                        </CardHeader>
                        <CardContent className="p-4 space-y-3">
                          <div className="flex items-center justify-between p-3 rounded-lg bg-muted/30 border border-border">
                            <div>
                              <div className="text-xs text-muted-foreground">Calibrated AI Indicator</div>
                              <div className="text-2xl font-bold text-foreground">
                                {result.aiGeneration.score}%
                              </div>
                            </div>
                            <div className="text-right">
                              <div className="text-xs text-muted-foreground">Confidence Level</div>
                              <div className="text-sm font-semibold text-foreground">
                                {result.aiGeneration.confidenceLevel} ({result.aiGeneration.confidenceScore}%)
                              </div>
                            </div>
                          </div>

                          <div className="space-y-1.5 text-xs">
                            <span className="font-semibold text-foreground">Forensic Findings:</span>
                            <ul className="list-disc list-inside space-y-1 text-muted-foreground">
                              {result.aiGeneration.reasoning.map((r, idx) => (
                                <li key={idx}>{r}</li>
                              ))}
                            </ul>
                          </div>

                          {result.aiGeneration.detectedGenerators.length > 0 && (
                            <div className="p-2.5 rounded-lg bg-red-500/10 border border-red-500/20 text-xs">
                              <span className="font-semibold text-red-600 block mb-1">
                                Identified Generator Signatures:
                              </span>
                              <div className="flex flex-wrap gap-1.5">
                                {result.aiGeneration.detectedGenerators.map((gen, idx) => (
                                  <Badge key={idx} variant="destructive" className="text-[10px]">
                                    {gen}
                                  </Badge>
                                ))}
                              </div>
                            </div>
                          )}
                        </CardContent>
                      </Card>

                      {/* 2. Image Manipulation & Tampering Card */}
                      <Card className="border-border bg-card shadow-sm flex flex-col justify-between">
                        <CardHeader className="py-3 px-4 border-b border-border bg-muted/20 flex flex-row items-center justify-between">
                          <CardTitle className="text-sm font-semibold text-foreground flex items-center gap-2">
                            <Layers className="w-4 h-4 text-amber-500" />
                            2. Manipulation & Tampering
                          </CardTitle>
                          <Badge
                            variant={
                              result.manipulation.verdict === 'AI editing indicated'
                                ? 'destructive'
                                : result.manipulation.verdict === 'No significant manipulation detected'
                                ? 'default'
                                : 'secondary'
                            }
                            className="text-xs font-semibold"
                          >
                            {result.manipulation.verdict}
                          </Badge>
                        </CardHeader>
                        <CardContent className="p-4 space-y-3">
                          <div className="grid grid-cols-2 gap-2 text-xs">
                            <div className="p-2.5 rounded-lg bg-muted/30 border border-border">
                              <div className="text-muted-foreground text-[11px]">Error Level (ELA) Delta</div>
                              <div className="text-base font-bold text-foreground">
                                {result.manipulation.elaDeltaScore} / 100
                              </div>
                            </div>
                            <div className="p-2.5 rounded-lg bg-muted/30 border border-border">
                              <div className="text-muted-foreground text-[11px]">Anomaly Clusters</div>
                              <div className="text-base font-bold text-foreground">
                                {result.manipulation.regionsDetected.length} Localized
                              </div>
                            </div>
                          </div>

                          <div className="space-y-1.5 text-xs">
                            <span className="font-semibold text-foreground">Manipulation Analysis:</span>
                            <ul className="list-disc list-inside space-y-1 text-muted-foreground">
                              {result.manipulation.reasoning.map((r, idx) => (
                                <li key={idx}>{r}</li>
                              ))}
                            </ul>
                          </div>
                        </CardContent>
                      </Card>

                      {/* 3. Provenance & C2PA Credentials Card */}
                      <Card className="border-border bg-card shadow-sm flex flex-col justify-between">
                        <CardHeader className="py-3 px-4 border-b border-border bg-muted/20 flex flex-row items-center justify-between">
                          <CardTitle className="text-sm font-semibold text-foreground flex items-center gap-2">
                            <FileCheck className="w-4 h-4 text-emerald-500" />
                            3. Provenance & C2PA Credentials
                          </CardTitle>
                          <Badge
                            variant={
                              result.provenance.c2paStatus === 'Valid trusted credentials'
                                ? 'default'
                                : 'secondary'
                            }
                            className="text-xs font-semibold"
                          >
                            {result.provenance.c2paStatus}
                          </Badge>
                        </CardHeader>
                        <CardContent className="p-4 space-y-3 text-xs">
                          {result.provenance.manifestPresent ? (
                            <div className="space-y-2">
                              <div className="p-2.5 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-800 dark:text-emerald-300">
                                <strong>Digital Signer:</strong> {result.provenance.claimGenerator || result.provenance.trustedIssuer || 'Verified Origin'}
                              </div>
                              <div className="text-muted-foreground">
                                Digital signing chain verified against public root certificate authorities.
                              </div>
                            </div>
                          ) : (
                            <p className="text-muted-foreground leading-relaxed">
                              No embedded JUMBF manifest or C2PA Content Credentials were found in the binary stream. Most social platforms strip metadata during upload.
                            </p>
                          )}
                          <div className="flex justify-between items-center pt-2 border-t border-border">
                            <span className="text-muted-foreground">EXIF Integrity:</span>
                            <Badge variant="outline" className="text-[10px]">
                              {result.provenance.exifIntegrity}
                            </Badge>
                          </div>
                        </CardContent>
                      </Card>

                      {/* 4. Metadata & Quality Assessment Card */}
                      <Card className="border-border bg-card shadow-sm flex flex-col justify-between">
                        <CardHeader className="py-3 px-4 border-b border-border bg-muted/20 flex flex-row items-center justify-between">
                          <CardTitle className="text-sm font-semibold text-foreground flex items-center gap-2">
                            <Camera className="w-4 h-4 text-blue-500" />
                            4. Quality & Sensor Inspection
                          </CardTitle>
                          <Badge
                            variant={result.quality.permitsReliableAnalysis ? 'default' : 'destructive'}
                            className="text-xs font-semibold"
                          >
                            {result.quality.qualityVerdict}
                          </Badge>
                        </CardHeader>
                        <CardContent className="p-4 space-y-2 text-xs">
                          <div className="grid grid-cols-2 gap-2">
                            <div className="p-2 rounded bg-muted/30 border border-border">
                              <span className="text-muted-foreground text-[11px]">Dimensions:</span>
                              <div className="font-semibold text-foreground">{result.quality.width} x {result.quality.height}</div>
                            </div>
                            <div className="p-2 rounded bg-muted/30 border border-border">
                              <span className="text-muted-foreground text-[11px]">Format & Blur:</span>
                              <div className="font-semibold text-foreground">{result.quality.mimeType} ({result.quality.blurLevel})</div>
                            </div>
                          </div>
                          <div className="p-2 rounded bg-muted/30 border border-border">
                            <span className="text-muted-foreground text-[11px]">Hardware / Camera Claim:</span>
                            <div className="font-semibold text-foreground truncate">
                              {result.provenance.cameraExif?.make
                                ? `${result.provenance.cameraExif.make} ${result.provenance.cameraExif.model || ''}`
                                : 'No camera hardware tag present'}
                            </div>
                          </div>
                        </CardContent>
                      </Card>
                    </div>

                    {/* Suspicious Region Visualizer */}
                    <ImageRegionInspectionOverlay result={result} />
                  </div>
                )}
              </TabsContent>

              {/* TAB 2: Compare Original vs Edit */}
              <TabsContent value="compare" className="mt-0">
                <ImageComparisonViewer />
              </TabsContent>

              {/* TAB 3: Batch Screening */}
              <TabsContent value="batch" className="mt-0">
                <BatchImageDetector />
              </TabsContent>
            </Tabs>
          </CardContent>
        </Card>
      </section>

      {/* ── SECTION 2: WHAT THE RESULT MEANS (Verdicts, Limitations & Calibrated Confidence) ── */}
      <section className="bg-muted/30 border-y border-border py-12 px-4 md:px-6">
        <div className="max-w-6xl mx-auto space-y-8">
          <div className="max-w-3xl space-y-2">
            <Badge variant="outline" className="text-xs font-semibold">
              Forensic Interpretation
            </Badge>
            <h2 className="text-2xl md:text-3xl font-bold text-foreground tracking-tight">
              What Your Image Analysis Result Means
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              AIDetector.cx evaluates probabilistic signals rather than making rigid binary guesses. Every score is calibrated to prevent false accusations while surfacing subtle generative artifacts.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            <Card className="border-border bg-card">
              <CardHeader className="pb-2">
                <Badge variant="destructive" className="w-fit text-xs mb-1">
                  Likely AI-Generated
                </Badge>
                <CardTitle className="text-base">Synthetic Diffusion Signatures</CardTitle>
              </CardHeader>
              <CardContent className="text-xs text-muted-foreground leading-relaxed space-y-2">
                <p>
                  High convergence across high-frequency Fourier residuals, synthetic pixel noise distributions, and repetitive generative textures (e.g. skin over-smoothing, unnatural pupil geometry).
                </p>
                <p className="text-foreground font-medium">
                  Confidence Score &gt;75%: Strong statistical evidence of diffusion generation.
                </p>
              </CardContent>
            </Card>

            <Card className="border-border bg-card">
              <CardHeader className="pb-2">
                <Badge variant="default" className="w-fit text-xs mb-1">
                  Likely Authentic
                </Badge>
                <CardTitle className="text-base">Natural Optical Sensor Profile</CardTitle>
              </CardHeader>
              <CardContent className="text-xs text-muted-foreground leading-relaxed space-y-2">
                <p>
                  Pixel noise patterns correlate with authentic camera sensor silicon (Bayer filter array, Poisson-Gaussian noise distributions) without generative frequency artifacts.
                </p>
                <p className="text-foreground font-medium">
                  Confidence Score &lt;25%: Low synthetic probability with natural sensor coherence.
                </p>
              </CardContent>
            </Card>

            <Card className="border-border bg-card">
              <CardHeader className="pb-2">
                <Badge variant="secondary" className="w-fit text-xs mb-1">
                  Suspected AI Manipulation
                </Badge>
                <CardTitle className="text-base">Localized Inpainting & Splicing</CardTitle>
              </CardHeader>
              <CardContent className="text-xs text-muted-foreground leading-relaxed space-y-2">
                <p>
                  The background shows natural optical noise, but specific regions (such as a face, hand, or inserted object) exhibit disparate Error Level Analysis (ELA) divergence and edge boundary warping.
                </p>
                <p className="text-foreground font-medium">
                  Indicates generative inpainting or composite manipulation.
                </p>
              </CardContent>
            </Card>
          </div>

          <Alert className="bg-background border-border">
            <Info className="w-4 h-4 text-primary" />
            <AlertTitle className="text-xs font-semibold">Calibrated Uncertainty & Limitations</AlertTitle>
            <AlertDescription className="text-xs text-muted-foreground mt-1 leading-relaxed">
              No AI detector should be treated as absolute judicial proof on its own. When an image has undergone severe downsampling (&lt;400px), multiple social media re-encodings, or extreme Gaussian blurring, high-frequency signals degrade, resulting in an <strong>Inconclusive</strong> verdict.
            </AlertDescription>
          </Alert>
        </div>
      </section>

      {/* ── SECTION 3: HOW AIDETECTOR.CX ANALYZES AN IMAGE (The Forensic Pipeline) ── */}
      <section className="max-w-6xl mx-auto px-4 md:px-6 py-12 space-y-8">
        <div className="max-w-3xl space-y-2">
          <Badge variant="outline" className="text-xs font-semibold">
            Technical Architecture
          </Badge>
          <h2 className="text-2xl md:text-3xl font-bold text-foreground tracking-tight">
            How AIDetector.cx Analyzes an Image
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Our multi-signal forensic pipeline fuses pixel-domain, frequency-domain, and cryptographic metadata checks to deliver transparent, explainable results.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="p-5 rounded-xl border border-border bg-card space-y-2.5">
            <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center text-primary">
              <Eye className="w-5 h-5" />
            </div>
            <h3 className="font-semibold text-sm text-foreground">1. Visual Artifacts & Textures</h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Evaluates anatomical coherence (corneal glints, ear symmetry, fingernails), background depth continuity, and fine prompt-rendering artifacts.
            </p>
          </div>

          <div className="p-5 rounded-xl border border-border bg-card space-y-2.5">
            <div className="w-9 h-9 rounded-lg bg-emerald-500/10 flex items-center justify-center text-emerald-500">
              <Layers className="w-5 h-5" />
            </div>
            <h3 className="font-semibold text-sm text-foreground">2. Error Level Analysis (ELA)</h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Computes compression differential maps across 8x8 DCT blocks to identify spliced regions saved at differing quantization quality levels.
            </p>
          </div>

          <div className="p-5 rounded-xl border border-border bg-card space-y-2.5">
            <div className="w-9 h-9 rounded-lg bg-blue-500/10 flex items-center justify-center text-blue-500">
              <Cpu className="w-5 h-5" />
            </div>
            <h3 className="font-semibold text-sm text-foreground">3. Laplacian Residual Noise</h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Isolates high-frequency sensor noise from structural image content using spatial Laplacian filters to detect diffusion model grid regularities.
            </p>
          </div>

          <div className="p-5 rounded-xl border border-border bg-card space-y-2.5">
            <div className="w-9 h-9 rounded-lg bg-purple-500/10 flex items-center justify-center text-purple-500">
              <FileCheck className="w-5 h-5" />
            </div>
            <h3 className="font-semibold text-sm text-foreground">4. C2PA & Provenance Validation</h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Parses binary JUMBF boxes to verify Adobe Content Credentials, camera hardware signatures, and digital tamper status against root CAs.
            </p>
          </div>
        </div>
      </section>

      {/* ── SECTION 4: AI-GENERATED VS. EDITED VS. AUTHENTIC (Comparison Matrix) ── */}
      <section className="bg-muted/30 border-y border-border py-12 px-4 md:px-6">
        <div className="max-w-6xl mx-auto space-y-8">
          <div className="max-w-3xl space-y-2">
            <Badge variant="outline" className="text-xs font-semibold">
              Classification Matrix
            </Badge>
            <h2 className="text-2xl md:text-3xl font-bold text-foreground tracking-tight">
              AI-Generated vs. Edited vs. Authentic Images
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Conventional photo adjustments (like Photoshop retouching or color grading) are not generative deepfakes. Here is how our detector distinguishes each category:
            </p>
          </div>

          <div className="w-full max-w-full overflow-x-auto bg-card rounded-xl border border-border shadow-sm">
            <table className="w-full text-xs text-left [&>div]:max-w-full">
              <thead className="bg-muted/60 text-foreground font-semibold border-b border-border">
                <tr>
                  <th className="p-3.5 whitespace-nowrap">Image Category</th>
                  <th className="p-3.5 whitespace-nowrap">Primary Forensic Characteristics</th>
                  <th className="p-3.5 whitespace-nowrap">Detector Verdict</th>
                  <th className="p-3.5 whitespace-nowrap">ELA Behavior</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border text-muted-foreground">
                <tr className="hover:bg-muted/10">
                  <td className="p-3.5 font-semibold text-foreground whitespace-nowrap">Fully AI-Generated</td>
                  <td className="p-3.5 whitespace-nowrap">Diffusion residual noise, absent EXIF sensor pipeline, synthetic frequency peaks</td>
                  <td className="p-3.5 whitespace-nowrap"><Badge variant="destructive" className="text-[10px]">Likely AI-Generated</Badge></td>
                  <td className="p-3.5 whitespace-nowrap">Uniform synthetic compression error map</td>
                </tr>
                <tr className="hover:bg-muted/10">
                  <td className="p-3.5 font-semibold text-foreground whitespace-nowrap">Generative Inpainting / Face Swap</td>
                  <td className="p-3.5 whitespace-nowrap">Boundary blending artifacts, localized frequency divergence on facial region</td>
                  <td className="p-3.5 whitespace-nowrap"><Badge variant="secondary" className="text-[10px] bg-amber-500/10 text-amber-600 border-amber-500/30">Suspected AI Manipulation</Badge></td>
                  <td className="p-3.5 whitespace-nowrap">Localized high-divergence error spike</td>
                </tr>
                <tr className="hover:bg-muted/10">
                  <td className="p-3.5 font-semibold text-foreground whitespace-nowrap">Photoshop / Global Retouching</td>
                  <td className="p-3.5 whitespace-nowrap">Uniform color grading, unwarped edges, coherent camera noise pattern</td>
                  <td className="p-3.5 whitespace-nowrap"><Badge variant="outline" className="text-[10px]">Conventional Editing</Badge></td>
                  <td className="p-3.5 whitespace-nowrap">Low localized divergence without synthetic noise</td>
                </tr>
                <tr className="hover:bg-muted/10">
                  <td className="p-3.5 font-semibold text-foreground whitespace-nowrap">Authentic Camera Capture</td>
                  <td className="p-3.5 whitespace-nowrap">Consistent sensor silicon noise, valid EXIF header, natural lighting vectors</td>
                  <td className="p-3.5 whitespace-nowrap"><Badge variant="default" className="text-[10px]">Likely Authentic</Badge></td>
                  <td className="p-3.5 whitespace-nowrap">Evenly distributed natural error pattern</td>
                </tr>
                <tr className="hover:bg-muted/10">
                  <td className="p-3.5 font-semibold text-foreground whitespace-nowrap">Heavy Social Re-compression</td>
                  <td className="p-3.5 whitespace-nowrap">Extreme quantization noise, downsampled pixel grid (&lt;400px), stripped EXIF</td>
                  <td className="p-3.5 whitespace-nowrap"><Badge variant="secondary" className="text-[10px]">Inconclusive</Badge></td>
                  <td className="p-3.5 whitespace-nowrap">Severe quantization masking fine residuals</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* ── SECTION 5: FALSE POSITIVE DEFENSE (Balanced Mode & Compression Robustness) ── */}
      <section className="max-w-6xl mx-auto px-4 md:px-6 py-12 space-y-8">
        <div className="max-w-3xl space-y-2">
          <Badge variant="outline" className="text-xs font-semibold">
            False-Positive Protection
          </Badge>
          <h2 className="text-2xl md:text-3xl font-bold text-foreground tracking-tight">
            Why AIDetector.cx Protects Against False Positives
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Many free tools falsely accuse real photographers because compressed JPEGs look noisy. AIDetector.cx Balanced Mode incorporates compression compensation algorithms and lists real benign conditions:
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
          <div className="p-4 rounded-xl border border-border bg-card space-y-2">
            <h4 className="font-semibold text-foreground text-sm flex items-center gap-1.5">
              <CheckCircle2 className="w-4 h-4 text-emerald-500" /> Compression Compensation
            </h4>
            <p className="text-muted-foreground leading-relaxed">
              Compensates for WhatsApp, WeChat, and TikTok aggressive JPEG re-compression so quantization artifacts are not mislabeled as AI noise.
            </p>
          </div>

          <div className="p-4 rounded-xl border border-border bg-card space-y-2">
            <h4 className="font-semibold text-foreground text-sm flex items-center gap-1.5">
              <CheckCircle2 className="w-4 h-4 text-emerald-500" /> Multi-Signal Convergence
            </h4>
            <p className="text-muted-foreground leading-relaxed">
              Never makes an AI verdict based on a single heuristic. Requires multi-layer consensus between ELA, frequency residuals, and metadata.
            </p>
          </div>

          <div className="p-4 rounded-xl border border-border bg-card space-y-2">
            <h4 className="font-semibold text-foreground text-sm flex items-center gap-1.5">
              <CheckCircle2 className="w-4 h-4 text-emerald-500" /> Legitimate Filter Recognition
            </h4>
            <p className="text-muted-foreground leading-relaxed">
              Recognizes digital illustrations, smartphone Night Mode computational photography, and cosmetic smoothing as non-generative.
            </p>
          </div>
        </div>
      </section>

      {/* ── SECTION 6: HOW TO USE THE FREE AI IMAGE DETECTOR (3 Concise Steps) ── */}
      <section className="bg-muted/30 border-y border-border py-12 px-4 md:px-6">
        <div className="max-w-6xl mx-auto space-y-8">
          <div className="text-center max-w-2xl mx-auto space-y-2">
            <Badge variant="outline" className="text-xs font-semibold">
              Simple Workflow
            </Badge>
            <h2 className="text-2xl md:text-3xl font-bold text-foreground tracking-tight">
              How to Use the Free AI Image Detector Online
            </h2>
            <p className="text-xs md:text-sm text-muted-foreground">
              Verify any photo in three fast, evidence-based steps.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="p-6 rounded-2xl border border-border bg-card text-center space-y-3">
              <div className="w-12 h-12 rounded-xl bg-primary/10 text-primary font-bold text-lg flex items-center justify-center mx-auto">
                1
              </div>
              <h3 className="font-bold text-sm text-foreground">Upload or Paste Image</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Drag and drop your file, paste directly from clipboard, or enter an image URL. Supports JPEG, PNG, WEBP, AVIF, HEIC up to 25MB.
              </p>
            </div>

            <div className="p-6 rounded-2xl border border-border bg-card text-center space-y-3">
              <div className="w-12 h-12 rounded-xl bg-primary/10 text-primary font-bold text-lg flex items-center justify-center mx-auto">
                2
              </div>
              <h3 className="font-bold text-sm text-foreground">Choose Detection Mode</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Select <strong>Balanced Mode</strong> for high false-positive resistance or <strong>High-Sensitivity</strong> to detect minor inpainting traces.
              </p>
            </div>

            <div className="p-6 rounded-2xl border border-border bg-card text-center space-y-3">
              <div className="w-12 h-12 rounded-xl bg-primary/10 text-primary font-bold text-lg flex items-center justify-center mx-auto">
                3
              </div>
              <h3 className="font-bold text-sm text-foreground">Review Verdict & Export</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Inspect the calibrated confidence indicator, ELA heatmap, and C2PA signature. Download a PDF certificate or JSON payload.
              </p>
            </div>
          </div>

          <div className="text-center pt-2">
            <Button size="lg" onClick={scrollToScanner} className="gap-2 font-bold text-xs">
              <Upload className="w-4 h-4" /> Start Image Scan Now
            </Button>
          </div>
        </div>
      </section>

      {/* ── SECTION 7: WHAT GENERATORS CAN BE ANALYZED? ── */}
      <section className="max-w-6xl mx-auto px-4 md:px-6 py-12 space-y-8">
        <div className="max-w-3xl space-y-2">
          <Badge variant="outline" className="text-xs font-semibold">
            Model Compatibility
          </Badge>
          <h2 className="text-2xl md:text-3xl font-bold text-foreground tracking-tight">
            What Image Generators Can Be Analyzed?
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            The detector evaluates images from known and unknown generation workflows. Performance can vary by model version, post-processing, and compression.
          </p>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3 text-xs">
          {[
            { name: 'OpenAI DALL-E 3 / ChatGPT', status: 'Benchmarked', badge: 'default' },
            { name: 'Midjourney (v5 / v6 / v7)', status: 'Benchmarked', badge: 'default' },
            { name: 'FLUX.1 (schnell / dev / pro)', status: 'Benchmarked', badge: 'default' },
            { name: 'Stable Diffusion (XL / SD3.5)', status: 'Benchmarked', badge: 'default' },
            { name: 'Google Imagen 3 / Gemini', status: 'Benchmarked', badge: 'default' },
            { name: 'Adobe Firefly (1 / 2 / 3)', status: 'C2PA Validated', badge: 'secondary' },
            { name: 'Ideogram 2.0', status: 'Benchmarked', badge: 'default' },
            { name: 'Leonardo AI / Photoreal', status: 'Benchmarked', badge: 'default' },
            { name: 'Canva Magic Media', status: 'Benchmarked', badge: 'default' },
            { name: 'Grok 2 / Flux Grok', status: 'Benchmarked', badge: 'default' },
            { name: 'Recraft V3', status: 'Benchmarked', badge: 'default' },
            { name: 'Custom LoRA & Fine-tunes', status: 'Diffusion Screened', badge: 'outline' },
          ].map((gen, idx) => (
            <div key={idx} className="p-3 rounded-xl border border-border bg-card flex flex-col justify-between gap-2">
              <span className="font-semibold text-foreground text-xs">{gen.name}</span>
              <Badge variant={gen.badge as any} className="text-[10px] w-fit">
                {gen.status}
              </Badge>
            </div>
          ))}
        </div>
      </section>

      {/* ── SECTION 8: KYC AND FRAUD SCREENING APPLICATIONS ── */}
      <section className="bg-muted/30 border-y border-border py-12 px-4 md:px-6">
        <div className="max-w-6xl mx-auto space-y-8">
          <div className="max-w-3xl space-y-2">
            <Badge variant="outline" className="text-xs font-semibold">
              Enterprise Risk Screening
            </Badge>
            <h2 className="text-2xl md:text-3xl font-bold text-foreground tracking-tight">
              AI Image Detection for KYC and Fraud Screening
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Designed to support KYC and fraud-screening workflows. Automated image detection provides early-warning risk signals to protect account onboarding, payment security, and insurance claims against synthetic identities.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            <div className="p-5 rounded-2xl border border-border bg-card space-y-2.5">
              <div className="w-10 h-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center">
                <Building2 className="w-5 h-5" />
              </div>
              <h3 className="font-bold text-sm text-foreground">Synthetic ID & Selfie Detection</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Flags generated face avatars (StyleGAN, FLUX portraits) and digitally modified government ID photos during customer onboarding.
              </p>
            </div>

            <div className="p-5 rounded-2xl border border-border bg-card space-y-2.5">
              <div className="w-10 h-10 rounded-xl bg-emerald-500/10 text-emerald-500 flex items-center justify-center">
                <FileCheck className="w-5 h-5" />
              </div>
              <h3 className="font-bold text-sm text-foreground">Insurance & Receipt Verification</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Identifies generative inpainting on vehicle damage claims, property loss photographs, and altered medical receipts.
              </p>
            </div>

            <div className="p-5 rounded-2xl border border-border bg-card space-y-2.5">
              <div className="w-10 h-10 rounded-xl bg-blue-500/10 text-blue-500 flex items-center justify-center">
                <Scale className="w-5 h-5" />
              </div>
              <h3 className="font-bold text-sm text-foreground">Audit Trails & Human Escalation</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Generates tamper-evident SHA-256 evidence certificates for compliance review. Risk signals guide human compliance officers rather than enforcing unreviewed automated bans.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ── SECTION 9: AI IMAGE DETECTION API ── */}
      <section className="max-w-6xl mx-auto px-4 md:px-6 py-12 space-y-8">
        <div className="max-w-3xl space-y-2">
          <Badge variant="outline" className="text-xs font-semibold">
            Developer Integration
          </Badge>
          <h2 className="text-2xl md:text-3xl font-bold text-foreground tracking-tight">
            AI Image Detection API
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Integrate enterprise-grade image authenticity checks directly into your content moderation queue, marketplace upload pipeline, or KYC workflow.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-center">
          <div className="space-y-4 text-xs text-muted-foreground leading-relaxed">
            <p>
              The AIDetector.cx REST API allows you to submit binary images or public URLs and receive structured JSON results including AI probability, Error Level Analysis metrics, C2PA claims, and detected model signatures.
            </p>
            <ul className="space-y-2 text-foreground">
              <li className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
                <span>Single & batch image submission (<code className="text-primary font-mono text-[11px]">POST /v1/images/detect</code>)</span>
              </li>
              <li className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
                <span>Zero retention in-memory processing guarantees data confidentiality</span>
              </li>
              <li className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
                <span>Standardized API keys, credit billing, and webhook notifications</span>
              </li>
            </ul>

            <div className="pt-2 flex flex-wrap gap-3">
              <Link to="/api-platform">
                <Button className="gap-2 text-xs font-semibold">
                  <Code2 className="w-4 h-4" /> Explore the AI Detection API
                </Button>
              </Link>
              <Link to="/api/docs">
                <Button variant="outline" className="gap-2 text-xs">
                  <ExternalLink className="w-3.5 h-3.5" /> View API Docs
                </Button>
              </Link>
            </div>
          </div>

          <div className="rounded-xl border border-border bg-slate-950 p-4 font-mono text-[11px] text-slate-200 overflow-x-auto shadow-md">
            <div className="text-slate-400 mb-2">// Sample JSON Response: POST /v1/images/detect</div>
            <pre className="text-emerald-400 leading-relaxed">
{`{
  "status": "success",
  "sha256": "8f3b20...91a2",
  "ai_generation": {
    "verdict": "Likely AI-generated",
    "score": 88,
    "confidence_level": "High",
    "detected_signatures": ["Midjourney v6", "Diffusion Residuals"]
  },
  "manipulation": {
    "detected": false,
    "ela_max_divergence_pct": 2.4
  },
  "c2pa": {
    "has_manifest": false
  }
}`}
            </pre>
          </div>
        </div>
      </section>

      {/* ── SECTION 10: HOW ACCURATE ARE AI IMAGE DETECTORS? ── */}
      <section className="bg-muted/30 border-y border-border py-12 px-4 md:px-6">
        <div className="max-w-6xl mx-auto space-y-8">
          <div className="max-w-3xl space-y-2">
            <Badge variant="outline" className="text-xs font-semibold">
              Empirical Accuracy & Benchmarking
            </Badge>
            <h2 className="text-2xl md:text-3xl font-bold text-foreground tracking-tight">
              How Accurate Are AI Image Detectors?
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Detection accuracy is not a single static number. Performance varies dynamically across image resolution, generative model architectures, compression, and post-processing filters.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2 space-y-4 text-xs text-muted-foreground leading-relaxed">
              <p>
                Detector output must always be interpreted as <strong>probabilistic forensic evidence</strong>, never as absolute judicial proof of human identity. When an image contains clean optical noise from a known camera sensor, confidence exceeds 95%. When an image has been saved multiple times across social media networks, fine diffusion residuals degrade.
              </p>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2">
                <div className="p-3.5 rounded-xl border border-border bg-card">
                  <h4 className="font-semibold text-foreground text-xs mb-1">Key Factors Increasing Accuracy:</h4>
                  <ul className="list-disc list-inside space-y-1 text-[11px]">
                    <li>Original camera captures with unstripped EXIF</li>
                    <li>Uncompressed PNG or high-bitrate WebP/JPEG</li>
                    <li>High native resolution (&gt;1024x1024px)</li>
                    <li>Presence of signed C2PA Content Credentials</li>
                  </ul>
                </div>
                <div className="p-3.5 rounded-xl border border-border bg-card">
                  <h4 className="font-semibold text-foreground text-xs mb-1">Key Factors Degrading Signals:</h4>
                  <ul className="list-disc list-inside space-y-1 text-[11px]">
                    <li>Aggressive social re-compression (e.g. WhatsApp)</li>
                    <li>Extreme downsampling (&lt;400px width)</li>
                    <li>Heavy Gaussian blurring or artistic filtering</li>
                    <li>Screen captures / phone photos of screens</li>
                  </ul>
                </div>
              </div>
            </div>

            {/* Benchmark Validation Card */}
            <Card className="border-border bg-card shadow-sm flex flex-col justify-between">
              <CardHeader className="pb-2">
                <div className="flex items-center justify-between">
                  <Badge variant="default" className="text-[10px]">
                    Pipeline v2.4 Benchmark
                  </Badge>
                  <span className="text-[10px] text-muted-foreground font-mono">Tested: Sep 2026</span>
                </div>
                <CardTitle className="text-sm font-bold mt-2">Curated 1,200 Sample Dataset</CardTitle>
                <CardDescription className="text-xs">
                  600 authentic camera captures vs 600 diffusion generations (MJ v6, DALL-E 3, FLUX.1, SDXL, Imagen 3).
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-3 text-xs pt-0">
                <div className="space-y-2">
                  <div className="flex justify-between items-center text-xs">
                    <span className="font-medium text-foreground">Balanced Mode Precision</span>
                    <span className="font-bold text-emerald-600 font-mono">94.2%</span>
                  </div>
                  <Progress value={94.2} className="h-1.5" />

                  <div className="flex justify-between items-center text-xs">
                    <span className="font-medium text-foreground">Balanced Mode Recall</span>
                    <span className="font-bold text-foreground font-mono">91.8%</span>
                  </div>
                  <Progress value={91.8} className="h-1.5" />

                  <div className="flex justify-between items-center text-xs">
                    <span className="font-medium text-foreground">False-Positive Rate</span>
                    <span className="font-bold text-amber-600 font-mono">3.1%</span>
                  </div>
                  <Progress value={3.1} className="h-1.5" />
                </div>

                <div className="p-2 rounded bg-muted/40 text-[11px] text-muted-foreground">
                  High-Sensitivity Mode increases Recall to 97.4% while raising False-Positive Rate to 9.8% for strict screening.
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* ── SECTION 11: CAN AI IMAGE DETECTORS BE BYPASSED? ── */}
      <section className="max-w-6xl mx-auto px-4 md:px-6 py-12 space-y-8">
        <div className="max-w-3xl space-y-2">
          <Badge variant="outline" className="text-xs font-semibold">
            Defensive Robustness
          </Badge>
          <h2 className="text-2xl md:text-3xl font-bold text-foreground tracking-tight">
            Can AI Image Detectors Be Bypassed?
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Adversarial techniques and severe compression can degrade individual detection signals. Here is why multi-signal fusion provides resilient protection without relying on a single failure point:
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          <div className="p-5 rounded-xl border border-border bg-card space-y-2">
            <h3 className="font-bold text-sm text-foreground flex items-center gap-2">
              <ShieldAlert className="w-4 h-4 text-primary" /> Evasion Techniques
            </h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Adversaries often apply subtle film grain, heavy compression, color grading, or cropping to disrupt frequency-domain Fourier peaks and confuse single-heuristic detectors.
            </p>
          </div>

          <div className="p-5 rounded-xl border border-border bg-card space-y-2">
            <h3 className="font-bold text-sm text-foreground flex items-center gap-2">
              <Layers className="w-4 h-4 text-emerald-500" /> Multi-Layer Fusion
            </h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              AIDetector.cx combines Error Level Analysis (ELA), Laplacian high-frequency residuals, EXIF integrity, C2PA claims, and lighting vector consistency so no single filter blinds the system.
            </p>
          </div>

          <div className="p-5 rounded-xl border border-border bg-card space-y-2">
            <h3 className="font-bold text-sm text-foreground flex items-center gap-2">
              <HelpCircle className="w-4 h-4 text-blue-500" /> Safe Uncertainty Handling
            </h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              When an image is too heavily distorted to evaluate with scientific confidence, our engine returns an honest <strong>Inconclusive</strong> verdict rather than generating an unreliable guess.
            </p>
          </div>
        </div>
      </section>

      {/* ── SECTION 12: WHAT MAKES A RELIABLE AI IMAGE DETECTOR? ── */}
      <section className="bg-muted/30 border-y border-border py-12 px-4 md:px-6">
        <div className="max-w-6xl mx-auto space-y-8">
          <div className="max-w-3xl space-y-2">
            <Badge variant="outline" className="text-xs font-semibold">
              Evaluation Criteria
            </Badge>
            <h2 className="text-2xl md:text-3xl font-bold text-foreground tracking-tight">
              What Makes a Reliable AI Image Detector?
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              When evaluating image authenticity tools, enterprise and consumer users should look for objective criteria rather than marketing claims:
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
            <div className="p-4 rounded-xl border border-border bg-card space-y-1.5">
              <span className="font-bold text-foreground text-sm flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-500" /> 1. False-Positive Mitigation & Dual Modes
              </span>
              <p className="text-muted-foreground leading-relaxed">
                Conservative default thresholds (Balanced Mode) ensure real photographers and authentic historical archives are not falsely accused.
              </p>
            </div>

            <div className="p-4 rounded-xl border border-border bg-card space-y-1.5">
              <span className="font-bold text-foreground text-sm flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-500" /> 2. Explainable Visual Forensics
              </span>
              <p className="text-muted-foreground leading-relaxed">
                Interactive Error Level Analysis (ELA) and Laplacian noise heatmaps allow users to see exactly which pixel clusters triggered flags.
              </p>
            </div>

            <div className="p-4 rounded-xl border border-border bg-card space-y-1.5">
              <span className="font-bold text-foreground text-sm flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-500" /> 3. Provenance & C2PA Validation
              </span>
              <p className="text-muted-foreground leading-relaxed">
                Direct parsing of Coalition for Content Provenance and Authenticity (C2PA) JUMBF binary boxes checks digital signatures against trusted root CAs.
              </p>
            </div>

            <div className="p-4 rounded-xl border border-border bg-card space-y-1.5">
              <span className="font-bold text-foreground text-sm flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-500" /> 4. Inpainting & Splicing Localization
              </span>
              <p className="text-muted-foreground leading-relaxed">
                Identifies localized modifications where a real background was merged with a generated subject or swapped face.
              </p>
            </div>

            <div className="p-4 rounded-xl border border-border bg-card space-y-1.5">
              <span className="font-bold text-foreground text-sm flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-500" /> 5. Strict Zero-Retention Privacy
              </span>
              <p className="text-muted-foreground leading-relaxed">
                Guarantees that uploaded files are processed in ephemeral memory without permanent storage or training use.
              </p>
            </div>

            <div className="p-4 rounded-xl border border-border bg-card space-y-1.5">
              <span className="font-bold text-foreground text-sm flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-500" /> 6. Enterprise REST API & Batch Ingestion
              </span>
              <p className="text-muted-foreground leading-relaxed">
                Provides scalable JSON endpoints for automated platform moderation and customer onboarding pipelines.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ── SECTION 13: COMPREHENSIVE USE CASES ── */}
      <section className="max-w-6xl mx-auto px-4 md:px-6 py-12 space-y-8">
        <div className="max-w-3xl space-y-2">
          <Badge variant="outline" className="text-xs font-semibold">
            Industry Applications
          </Badge>
          <h2 className="text-2xl md:text-3xl font-bold text-foreground tracking-tight">
            Who Uses AIDetector.cx AI Image Detector?
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            From breaking newsrooms to financial compliance teams, our forensic image suite serves diverse verification workflows:
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 text-xs">
          <div className="p-4 rounded-xl border border-border bg-card space-y-2">
            <div className="w-8 h-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center">
              <Newspaper className="w-4 h-4" />
            </div>
            <h3 className="font-bold text-sm text-foreground">Journalists & Fact-Checkers</h3>
            <p className="text-muted-foreground leading-relaxed">
              Verify viral social media images, citizen journalism footage, and press releases before publishing breaking stories.
            </p>
          </div>

          <div className="p-4 rounded-xl border border-border bg-card space-y-2">
            <div className="w-8 h-8 rounded-lg bg-emerald-500/10 text-emerald-500 flex items-center justify-center">
              <Palette className="w-4 h-4" />
            </div>
            <h3 className="font-bold text-sm text-foreground">Artists & Photographers</h3>
            <p className="text-muted-foreground leading-relaxed">
              Protect original visual portfolios against unauthorized AI scraping and demonstrate authentic human authorship.
            </p>
          </div>

          <div className="p-4 rounded-xl border border-border bg-card space-y-2">
            <div className="w-8 h-8 rounded-lg bg-blue-500/10 text-blue-500 flex items-center justify-center">
              <ShoppingBag className="w-4 h-4" />
            </div>
            <h3 className="font-bold text-sm text-foreground">Marketplaces & E-Commerce</h3>
            <p className="text-muted-foreground leading-relaxed">
              Screen fraudulent seller listings, synthetic mockups, and non-existent inventory on peer-to-peer commerce sites.
            </p>
          </div>

          <div className="p-4 rounded-xl border border-border bg-card space-y-2">
            <div className="w-8 h-8 rounded-lg bg-purple-500/10 text-purple-500 flex items-center justify-center">
              <UserCheck className="w-4 h-4" />
            </div>
            <h3 className="font-bold text-sm text-foreground">KYC & Identity Fraud Teams</h3>
            <p className="text-muted-foreground leading-relaxed">
              Identify AI-generated onboarding selfie avatars, manipulated driver license portraits, and synthetic bank documents.
            </p>
          </div>

          <div className="p-4 rounded-xl border border-border bg-card space-y-2">
            <div className="w-8 h-8 rounded-lg bg-amber-500/10 text-amber-500 flex items-center justify-center">
              <Scale className="w-4 h-4" />
            </div>
            <h3 className="font-bold text-sm text-foreground">Insurance Claim Adjusters</h3>
            <p className="text-muted-foreground leading-relaxed">
              Inspect submitted vehicle collision photos, property damage estimates, and repair receipts for generative inpainting.
            </p>
          </div>

          <div className="p-4 rounded-xl border border-border bg-card space-y-2">
            <div className="w-8 h-8 rounded-lg bg-indigo-500/10 text-indigo-500 flex items-center justify-center">
              <Server className="w-4 h-4" />
            </div>
            <h3 className="font-bold text-sm text-foreground">Platform Moderation Teams</h3>
            <p className="text-muted-foreground leading-relaxed">
              Automate platform trust and safety screening using high-throughput REST API webhooks to enforce synthetic media policies.
            </p>
          </div>
        </div>
      </section>

      {/* ── SECTION 14: PRIVACY AND UPLOADED IMAGES ── */}
      <section className="bg-muted/30 border-y border-border py-12 px-4 md:px-6">
        <div className="max-w-6xl mx-auto space-y-8">
          <div className="max-w-3xl space-y-2">
            <Badge variant="outline" className="text-xs font-semibold">
              Data Governance & Security
            </Badge>
            <h2 className="text-2xl md:text-3xl font-bold text-foreground tracking-tight">
              Privacy and Uploaded Images
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              We uphold strict data confidentiality and zero-retention principles across all image analysis workflows:
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-5 text-xs">
            <Card className="border-border bg-card">
              <CardHeader className="pb-2">
                <Lock className="w-5 h-5 text-emerald-500 mb-1" />
                <CardTitle className="text-sm font-bold">1. Ephemeral In-Memory Analysis</CardTitle>
              </CardHeader>
              <CardContent className="text-muted-foreground leading-relaxed">
                Uploaded image bytes are parsed in volatile RAM during the active request. No copies are saved to permanent disks or cloud storage buckets.
              </CardContent>
            </Card>

            <Card className="border-border bg-card">
              <CardHeader className="pb-2">
                <ShieldCheck className="w-5 h-5 text-primary mb-1" />
                <CardTitle className="text-sm font-bold">2. Zero Model Training</CardTitle>
              </CardHeader>
              <CardContent className="text-muted-foreground leading-relaxed">
                Customer files are never used to train, fine-tune, or calibrate future artificial intelligence models. Your proprietary media remains your own.
              </CardContent>
            </Card>

            <Card className="border-border bg-card">
              <CardHeader className="pb-2">
                <FileCheck className="w-5 h-5 text-blue-500 mb-1" />
                <CardTitle className="text-sm font-bold">3. Client-Side Cryptographic Hash</CardTitle>
              </CardHeader>
              <CardContent className="text-muted-foreground leading-relaxed">
                Evidence reports record a one-way SHA-256 cryptographic hash so audit certificates can be verified without storing the underlying image.
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* ── SECTION 15: 18 COMPREHENSIVE VISIBLE FAQS ── */}
      <section className="max-w-6xl mx-auto px-4 md:px-6 py-12 space-y-8">
        <div className="max-w-3xl space-y-2">
          <Badge variant="outline" className="text-xs font-semibold">
            Frequently Asked Questions
          </Badge>
          <h2 className="text-2xl md:text-3xl font-bold text-foreground tracking-tight">
            Frequently Asked Questions About AI Image Detection
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Detailed, technically accurate answers to common questions about artificial intelligence image detection, Error Level Analysis, and verification.
          </p>
        </div>

        <Accordion type="single" collapsible className="w-full space-y-3">
          {FAQ_ITEMS.map((faq, idx) => (
            <AccordionItem
              key={idx}
              value={`item-${idx}`}
              className="border border-border rounded-xl px-4 bg-card shadow-sm"
            >
              <AccordionTrigger className="text-sm font-semibold text-foreground hover:no-underline py-4 text-left">
                {faq.q}
              </AccordionTrigger>
              <AccordionContent className="text-xs text-muted-foreground leading-relaxed pb-4 pt-1">
                {faq.a}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </section>

      {/* ── SISTER TOOLS NAVIGATION & FOOTER CONVERSION ── */}
      <section className="bg-muted/30 border-t border-border py-12 px-4 md:px-6">
        <div className="max-w-6xl mx-auto space-y-8">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <h3 className="text-lg font-bold text-foreground">Explore Related Forensic Tools</h3>
              <p className="text-xs text-muted-foreground mt-0.5">
                Comprehensive multi-modal content detection suite for audio, video, deepfakes, and text.
              </p>
            </div>
            <Link to="/detector">
              <Button variant="outline" size="sm" className="gap-1.5 text-xs">
                View All Detectors <ArrowRight className="w-3.5 h-3.5" />
              </Button>
            </Link>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
            <Link to="/ai-video-detector" className="p-3.5 rounded-xl border border-border bg-card hover:border-primary transition-colors block">
              <div className="font-semibold text-foreground">AI Video Detector</div>
              <div className="text-[11px] text-muted-foreground mt-0.5">Frame-by-frame forensics</div>
            </Link>
            <Link to="/detector?tab=voice" className="p-3.5 rounded-xl border border-border bg-card hover:border-primary transition-colors block">
              <div className="font-semibold text-foreground">AI Voice Detector</div>
              <div className="text-[11px] text-muted-foreground mt-0.5">Audio cloning & deepfake audio</div>
            </Link>
            <Link to="/detector?tab=text" className="p-3.5 rounded-xl border border-border bg-card hover:border-primary transition-colors block">
              <div className="font-semibold text-foreground">AI Text Detector</div>
              <div className="text-[11px] text-muted-foreground mt-0.5">ChatGPT & Claude text checker</div>
            </Link>
            <Link to="/api-platform" className="p-3.5 rounded-xl border border-border bg-card hover:border-primary transition-colors block">
              <div className="font-semibold text-foreground">Enterprise REST API</div>
              <div className="text-[11px] text-muted-foreground mt-0.5">High-throughput moderation</div>
            </Link>
          </div>
        </div>
      </section>

      {/* Feedback Modal */}
      {feedbackOpen && result && (
        <ReportIncorrectResultModal
          open={feedbackOpen}
          onOpenChange={setFeedbackOpen}
          imageId={result.id}
          imageHash={result.sha256}
          reportedVerdict={result.aiGeneration.verdict}
        />
      )}
    </MainLayout>
  );
}
