import { serve } from "https://deno.land/std/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { text, mode } = await req.json();
    if (!text) {
      throw new Error('Text is required');
    }
    
    if (!['ai', 'plagiarism', 'hallucination'].includes(mode)) {
      throw new Error('Valid mode is required (ai, plagiarism, hallucination)');
    }

    const apiKey = Deno.env.get('INTEGRATIONS_API_KEY');
    if (!apiKey) {
      throw new Error('Server configuration error (missing key)');
    }

    let systemPrompt = "";
    
    if (mode === 'ai') {
      systemPrompt = `You are an advanced AI text detection engine like ZeroGPT or Originality.ai. Your task is to analyze the provided text and determine if it was written by a human or generated by an AI model (like ChatGPT, Claude, Gemini, etc.).
Analyze the text at the paragraph and sentence level. Consider perplexity, burstiness, pattern repetitiveness, emotional language, personal anecdotes, and overall flow.

You MUST respond strictly with a valid JSON object matching this schema (do NOT wrap it in Markdown tags, just output the raw JSON object):
{
  "aiProbability": number, // 0-100
  "confidenceScore": number, // 0-100
  "riskLevel": "High" | "Medium" | "Low" | "Critical",
  "paragraphTimeline": [
    { "aiProbability": number } // 0-100 for each paragraph
  ],
  "sentences": [
    {
      "text": "The sentence text.",
      "aiProbability": number, // 0-100
      "perplexityScore": number,
      "burstinessScore": number
    }
  ],
  "humanEvidence": {
    "score": number, // 0-100
    "indicators": ["List of indicators like 'emotional language', 'personal anecdote', 'unique phrasing'"]
  },
  "fingerprint": {
    "primaryModel": "ChatGPT" | "Claude" | "Gemini" | "Human" | "Unknown",
    "primaryConfidence": number,
    "secondaryModel": "string or omit",
    "secondaryConfidence": number
  }
}

Text to analyze:
"""
${text}
"""`;
    } else if (mode === 'plagiarism') {
      systemPrompt = `You are an advanced plagiarism detection engine. Analyze the provided text for potential plagiarism, including exact matches, partial matches, AI paraphrasing, and patchwork plagiarism.

You MUST respond strictly with a valid JSON object matching this schema:
{
  "originalityScore": number, // 0-100
  "riskLevel": "High" | "Medium" | "Low" | "Critical",
  "matchTypes": {
    "exact": number, // percentage 0-100
    "partial": number,
    "aiParaphrased": number,
    "patchwork": number
  },
  "sources": [
    {
      "url": "Simulated source URL matching the content",
      "similarity": number, // 0-100
      "matchLength": number, // word count
      "matchType": "Exact" | "Partial" | "AI Paraphrased" | "Patchwork"
    }
  ]
}

Text to analyze:
"""
${text}
"""`;
    } else if (mode === 'hallucination') {
      systemPrompt = `You are an advanced hallucination detection engine. Extract factual claims from the provided text and verify them. Check for unsupported facts, fabricated statistics, and questionable logic.

You MUST respond strictly with a valid JSON object matching this schema:
{
  "hallucinationRiskScore": number, // 0-100
  "riskLevel": "High" | "Medium" | "Low" | "Critical",
  "claims": [
    {
      "text": "The factual claim extracted from text.",
      "status": "Verified" | "Questionable" | "Unsupported",
      "confidence": number, // 0-100
      "evidence": "Explanation of why it is verified or unsupported"
    }
  ],
  "issues": [
    {
      "type": "fabricated-statistic" | "fake-citation" | "unsupported-claim",
      "description": "Description of the issue"
    }
  ],
  "summary": {
    "total": number,
    "verified": number,
    "questionable": number,
    "unsupported": number
  }
}

Text to analyze:
"""
${text}
"""`;
    }

    const upstream = await fetch(
      "https://app-c18l1vf2nz7l-api-VaOwP8E7dJqa.gateway.appmedo.com/v1beta/models/gemini-2.5-flash:generateContent",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-Gateway-Authorization": `Bearer ${apiKey}`,
        },
        body: JSON.stringify({
          contents: [{ role: "user", parts: [{ text: systemPrompt }] }],
          generationConfig: {
            responseMimeType: "application/json"
          }
        }),
      }
    );

    if (!upstream.ok) {
      const errText = await upstream.text();
      if (upstream.status === 404 || upstream.status === 500) {
        console.error("Non-stream failed, falling back to streamGenerateContent", errText);
      } else {
         throw new Error(`Upstream API failed: ${upstream.status} ${errText}`);
      }
    }

    let resultJson = null;
    if (upstream.ok) {
       const resData = await upstream.json();
       const rawText = resData.candidates?.[0]?.content?.parts?.[0]?.text || "{}";
       try {
         const cleanText = rawText.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
         resultJson = JSON.parse(cleanText);
       } catch(e) {
         console.error("Failed to parse JSON:", rawText);
         throw e;
       }
    } else {
       // Fallback to streaming endpoint if non-streaming not allowed
       const fallbackUpstream = await fetch(
          "https://app-c18l1vf2nz7l-api-VaOwP8E7dJqa.gateway.appmedo.com/v1beta/models/gemini-2.5-flash:streamGenerateContent?alt=sse",
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "X-Gateway-Authorization": `Bearer ${apiKey}`,
            },
            body: JSON.stringify({
              contents: [{ role: "user", parts: [{ text: systemPrompt }] }],
            }),
          }
        );
        if (!fallbackUpstream.ok) throw new Error("Fallback upstream failed");
        
        const reader = fallbackUpstream.body?.getReader();
        const decoder = new TextDecoder();
        let fullText = "";
        let buffer = "";
        if (reader) {
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            buffer += decoder.decode(value, { stream: true });
            const lines = buffer.split('\n');
            buffer = lines.pop() || '';
            for (const line of lines) {
              if (line.startsWith('data: ') && line !== 'data: [DONE]') {
                try {
                   const data = JSON.parse(line.slice(5));
                   if (data.candidates?.[0]?.content?.parts?.[0]?.text) {
                     fullText += data.candidates[0].content.parts[0].text;
                   }
                } catch(e) {}
              }
            }
          }
        }
        
        try {
           const cleanText = fullText.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
           resultJson = JSON.parse(cleanText);
        } catch(e) {
           throw new Error("Failed to parse JSON from stream: " + fullText);
        }
    }

    return new Response(JSON.stringify(resultJson), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error: any) {
    console.error("advanced-detector error:", error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});