import { Link } from 'react-router-dom';
import MainLayout from '@/components/layouts/MainLayout';
import PageMeta from '@/components/common/PageMeta';
import BloggerSEOWorkspace from './BloggerSEOWorkspace';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { ArrowRight, Bot, CheckCircle2, FileSearch, Search, ShieldCheck, Sparkles, Target } from 'lucide-react';

const FAQS = [
  { q: 'What is an AI checker for bloggers?', a: 'An AI checker for bloggers helps review a draft for machine-writing signals before publication. A useful publishing workflow also checks originality, plagiarism, search intent, readability and other content-quality signals rather than relying on one AI percentage.' },
  { q: 'Can I paste my blog article directly into this page?', a: 'Yes. You can paste or write your article directly in the Blogger SEO Workspace. The analysis runs from your content, while detailed scores and recommendations are revealed to active paid members.' },
  { q: 'Is the Blogger SEO Workspace free?', a: 'The editor can be opened from this page, but detailed Blogger SEO Workspace analysis is reserved for active paid members and uses the existing AIDetector.cx SEO Assistant entitlement and credit system. There is no separate blogger subscription.' },
  { q: 'Does Google penalize blog posts just because AI was used?', a: 'Google guidance focuses on the quality and usefulness of content rather than treating AI use by itself as an automatic penalty. Bloggers should prioritize original, accurate, people-first content and avoid scaled low-value publishing.' },
  { q: 'Can an AI detector be 100% accurate?', a: 'No responsible AI detector should be treated as perfect. Detection is probabilistic. Review flagged passages in context and combine detection with source checking, plagiarism analysis and human editorial judgment.' },
  { q: 'Should I rewrite every sentence flagged as AI?', a: 'No. A flag is a reason to inspect a passage, not an automatic rewrite instruction. Check whether it is repetitive, generic, unsupported or inconsistent with the author’s normal voice.' },
  { q: 'Can I check plagiarism and SEO as part of the same publishing workflow?', a: 'Yes. AIDetector.cx combines AI detection, multilingual plagiarism checking and SEO-focused analysis so bloggers can review several publishing risks before going live.' },
];

const workflow = [
  { icon: Bot, title: 'AI-writing signals', text: 'Review AI probability and sentence-level signals with the AI Detector.', href: '/detector', cta: 'AI Detector' },
  { icon: FileSearch, title: 'Originality & plagiarism', text: 'Check overlap against web and academic sources before publishing.', href: '/plagiarism-checker', cta: 'Plagiarism Checker' },
  { icon: Search, title: 'SEO & publishing readiness', text: 'Inspect intent, semantics, readability, headings, E-E-A-T, links and snippet potential.', href: '#blogger-workspace', cta: 'Blogger SEO Workspace' },
];

export default function AICheckerForBloggersPage() {
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: FAQS.map((faq) => ({ '@type': 'Question', name: faq.q, acceptedAnswer: { '@type': 'Answer', text: faq.a } })) };
  const softwareSchema = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'AIDetector.cx AI Checker for Bloggers', applicationCategory: 'BusinessApplication', operatingSystem: 'Web', url: 'https://aidetector.cx/ai-checker-for-bloggers', description: 'A paid pre-publication workspace for bloggers combining AI detection, plagiarism review, SEO analysis, readability and publishing-readiness guidance.' };

  return <MainLayout>
    <PageMeta title="AI Checker for Bloggers: AI, Plagiarism & SEO Review | AIDetector.cx" description="Paste your blog article and review AI-writing signals, plagiarism, SEO, readability and publishing readiness. Built for bloggers, editors and content teams." canonicalUrl="https://aidetector.cx/ai-checker-for-bloggers" ogTitle="AI Checker for Bloggers & SEO Publishing Workspace | AIDetector.cx" ogDescription="Review AI signals, originality, SEO quality and publishing readiness before your blog post goes live." schemas={[softwareSchema, faqSchema]} />

    <section className="relative overflow-hidden border-b border-border/60 bg-background"><div className="absolute inset-0 bg-gradient-to-b from-primary/10 via-background to-background"/><div className="relative mx-auto max-w-7xl px-4 pb-12 pt-10 md:px-6 md:pb-16 md:pt-16"><div className="mx-auto max-w-4xl text-center"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-4 py-2 text-sm font-medium text-primary"><Sparkles className="h-4 w-4"/> AI + plagiarism + SEO publishing review</div><h1 className="text-balance text-4xl font-bold tracking-tight md:text-6xl">AI Checker for Bloggers</h1><p className="mx-auto mt-5 max-w-3xl text-pretty text-lg leading-8 text-muted-foreground md:text-xl">Paste your article and review AI-writing signals, plagiarism, SEO quality, readability and publishing readiness before you hit Publish.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Button size="lg" asChild className="h-12 px-7"><a href="#blogger-workspace">Paste My Article <ArrowRight className="ml-2 h-4 w-4"/></a></Button><Button size="lg" variant="outline" asChild className="h-12 px-7"><Link to="/pricing">View Paid Plans</Link></Button></div><p className="mt-4 text-sm text-muted-foreground"><ShieldCheck className="mr-1 inline h-4 w-4"/> You can paste content before signing in. Detailed SEO analysis is revealed to active paid members. AI detection is probabilistic evidence, not proof of authorship.</p></div></div></section>

    <BloggerSEOWorkspace />

    <section className="py-14 md:py-20"><div className="mx-auto max-w-7xl px-4 md:px-6"><div className="mx-auto max-w-3xl text-center"><div className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><Target className="h-4 w-4"/> One workflow before you publish</div><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">Go beyond a single AI percentage</h2><p className="mt-4 text-lg leading-8 text-muted-foreground">Bloggers need a publishing decision, not another isolated score. Use multiple signals to find what deserves review before a post goes live.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{workflow.map(({icon:Icon,title,text,href,cta})=><Card key={title} className="h-full"><CardContent className="p-6"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5"/></div><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p>{href.startsWith('#')?<a href={href} className="mt-4 inline-flex items-center text-sm font-semibold text-primary hover:underline">{cta}<ArrowRight className="ml-1 h-4 w-4"/></a>:<Link to={href} className="mt-4 inline-flex items-center text-sm font-semibold text-primary hover:underline">{cta}<ArrowRight className="ml-1 h-4 w-4"/></Link>}</CardContent></Card>)}</div></div></section>

    <section className="border-y border-border/60 bg-muted/30 py-14 md:py-20"><div className="mx-auto grid max-w-7xl gap-10 px-4 md:px-6 lg:grid-cols-2 lg:items-center"><div><h2 className="text-3xl font-bold tracking-tight md:text-4xl">How to interpret an AI score on a blog post</h2><div className="mt-5 space-y-4 leading-7 text-muted-foreground"><p>An AI score estimates how strongly writing patterns resemble machine-generated or human-written text. It is not a verdict on authorship. Polished human prose can look predictable, while heavily edited AI-assisted writing can appear less predictable.</p><p>Inspect where the strongest signals occur. Repetitive transitions, formulaic introductions, unsupported claims and unusually uniform sentence structures may deserve editorial attention. Do not rewrite strong, accurate passages merely to chase a detector score.</p><p>The goal is a better article: original experience where relevant, accurate claims, useful examples, transparent sourcing and a structure that satisfies the reader’s search intent.</p></div></div><Card><CardContent className="p-7"><h3 className="text-xl font-semibold">What the paid workspace reviews</h3><div className="mt-5 grid gap-3 sm:grid-cols-2">{['Search intent match','Semantic keyword coverage','Readability','Grammar & spacing','Heading structure','E-E-A-T signals','Internal linking','Snippet potential','Content uniqueness','Publishing readiness'].map(x=><div key={x} className="flex gap-2 text-sm"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>{x}</div>)}</div></CardContent></Card></div></section>

    <section className="py-14 md:py-20"><div className="mx-auto max-w-7xl px-4 md:px-6"><div className="grid gap-5 lg:grid-cols-3">{[['Independent bloggers','Review long-form drafts without reducing editorial judgment to a single detector percentage.',Bot],['Editors & publishers','Apply a repeatable review workflow to freelancer, contributor and agency submissions.',FileSearch],['SEO content teams','Connect content-integrity review with search intent, semantic coverage, readability and internal linking.',Search]].map(([title,text,Icon]: any)=><Card key={title}><CardContent className="p-7"><Icon className="h-7 w-7 text-primary"/><h2 className="mt-4 text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-muted-foreground">{text}</p></CardContent></Card>)}</div></div></section>

    <section className="bg-muted/30 py-14 md:py-20"><div className="mx-auto max-w-4xl px-4 md:px-6"><h2 className="text-center text-3xl font-bold tracking-tight md:text-4xl">Frequently asked questions</h2><Accordion type="single" collapsible className="mt-8 rounded-xl border border-border bg-background px-5 md:px-7">{FAQS.map((faq,index)=><AccordionItem key={faq.q} value={`faq-${index}`}><AccordionTrigger className="text-left text-base font-semibold md:text-lg">{faq.q}</AccordionTrigger><AccordionContent className="pb-5 text-base leading-7 text-muted-foreground">{faq.a}</AccordionContent></AccordionItem>)}</Accordion></div></section>

    <section className="py-14 md:py-20"><div className="mx-auto max-w-5xl px-4 text-center md:px-6"><div className="rounded-3xl border border-primary/20 bg-gradient-to-b from-primary/10 to-background p-8 md:p-12"><Sparkles className="mx-auto h-8 w-8 text-primary"/><h2 className="mt-4 text-3xl font-bold">Review your next blog post before it goes live</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-muted-foreground">Paste the article directly into the Blogger SEO Workspace, let the analysis run, then unlock the detailed scores and recommendations with an active paid plan.</p><Button asChild size="lg" className="mt-7"><a href="#blogger-workspace">Paste My Article <ArrowRight className="ml-2 h-4 w-4"/></a></Button></div></div></section>
  </MainLayout>;
}
